### ISSUE TITLE
Gmsh binary handling not robust

### ISSUE THREAD

**Issue by dbeurle** [rquey/neper#11]
When running a development build of gmsh, the `neper -M -gmsh $(which gmsh)` (`/usr/local/bin/gmsh`) fails with
```
You have to specify a valid access path to the gmsh binary
Aborted (core dumped)
```
Which doesn't provide the second half of the message on line 45 since the output wasn't flushed.

Is it possible to make this a little more robust to handle development builds?  I want to use this as a test case for profiling gmsh.

Also - compiling neper with gcc 8 gives lots of warnings about misleading indents, deprecated features and other problems.

**Comment by avillani** [comment]
hello,

I'm running gmsh 3.0.6, binary version. It's in `/opt/gmsh/3/bin/gmsh`
 Did you compile gmsh from source ?

I have no problem with `neper -M -gmsh $(which gmsh)`. What is your neper version ?

**Comment by dbeurle** [comment]
Current stable version from http://neper.sourceforge.net/downloads.html

**Comment by avillani** [comment]
So, I assume gmsh has been compiled from source ? You didn't really answer.

With neper stable version from sourceforge, and manually installed gmsh binary from gmsh website:
```
./neper  -M -gmsh $(which gmsh)

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 3.2.0
Info   : Built with: gsl nlopt openmp
Info   : Running on 8 threads.
Info   : <http://neper.sourceforge.net>
Info   : Copyright (C) 2003-2018, and GNU GPL'd, by Romain Quey.
Info   : Comments and bug reports: <neper-users@lists.sourceforge.net>.
Info   : No initialization file found (`/home/avillani/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -gmsh /opt/gmsh/3/bin/gmsh
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   : Elapsed time: 0.032 secs.
========================================================================
```

**Comment by dbeurle** [comment]
Sorry I misread your question.  Typically locally compiled source versions are placed into `/usr/local/bin`.  If it got there otherwise I'd be concerned ;)

Yes - but I *think* the problem is in the `--version` string of gmsh.  Does your `gmsh --version` output a clean `3.0.6` or is there a git tag at the end?

**Comment by avillani** [comment]
Just `3.0.6`. I'll try to use a lcoally compiled version.

**Comment by dbeurle** [comment]
Thanks - that would be really helpful.

**Comment by dbeurle** [comment]
Thank you very much everyone :)
