### ISSUE TITLE
Faset faset_elt_id does not appear to correspond to surface (1..3D) element number

### ISSUE THREAD

**Issue by rcarson3** [rquey/neper#113]
@rquey so as part of working on a script to get a `gmsh` file that only has the surface faces for the 2D element attributes for #59 I ran into some issues while using what was outputted by `-faset`. I would have expected the `-faset` option to return the surface mesh element ids. Based on the description of  `faset_elt_id`, I would assume that value to correspond to the global element element ID that corresponds to elements for a given surface. However, I found that this was not the case while writing a python script to parse and automatically create a msh file for my use case. I can post that script if there is interest. 

I've come up with a minimal working example to showcase what I'm talking about using neper v4.1.1:

```
neper -T -n1 -o n1
neper -M n1.tess -o n1 -format 'msh' -faset 'faces' -order 1
```

I've attached the gmsh v2.2 file that's outputted from the above.
[n1.txt](https://github.com/rquey/neper/files/5985780/n1.txt)

In this simple example, when looking at `PhysicalNames` : I would expect `face1` -  `face6` and their 2D elements to correspond to the elements listed in `x0,x1,y0,y1,z0,z1`. However, it doesn't appear that is the case. Therefore, I'm not really too sure what `faset_elt_id` actually corresponds to.

**Comment by rquey** [comment]
Thanks @rcarson3 for the detailed bug report, it's very much appreciated.

This was a simple bug. In the `msh` file, the elements of all dimensions are written, and so the 3D elements do not start at 1. This was not taken into account when writing the `$Fasets` section.

**Comment by rcarson3** [comment]
Thanks @rquey for the quick fix and explanation. I actually didn't realize that the values in the `$Fasets` section corresponded to 3D element IDs that actually simplified my life a bit, since I can directly create the appropriate 2D elements just from the supplied node information and output a modified gmsh file for my users using this [script](https://github.com/LLNL/ExaConstit/blob/ea0ce63c1538264adcd2be8f0cb7bc1fadc1ebab/scripts/meshing/neper_v4_mesh.py).
