### ISSUE TITLE
Problem meshing 3D

### ISSUE THREAD

**Issue by J-AKAZ** [rquey/neper#137]
Starting with:
```
$ neper -T -n 3280 -domain 'cube(0.03,0.03,0.01)' -morpho gg  -reg 1 -o microstructure
```

It works 
Then 

```
$ neper -M microstructure.tess -clmin 0.0001 -elttype tet -statelt elset3d -meshqualmin 1 -o microstructure

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.1.2
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 24 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/g20281/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] microstructure.tess -clmin 0.0001 -elttype tet
         -statelt elset3d -meshqualmin 1 -o microstructure
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `microstructure.tess'...
Info   :     [i] Parsed file `microstructure.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.0007) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing...  10% (0.1|0.76/98%| 1%| 1%)  
*pbnodeqty = 6
nodeqty1d = 5
min_dist_max = 0.000399
Abandon
``

I tried with different values of -cl but it doesn't work... Could you help me please!
Thanks in advance

**Comment by rquey** [comment]
It works perfectly for me. What is your system? Gmsh version?

**Comment by J-AKAZ** [comment]
Hello,
Thank you for your reply.
Actually, it's a SCIBIAN 9 48Go RAM.
For the Gmsh i have 2.15.0

**Comment by rquey** [comment]
Can you try with a recent Gmsh version? It should work with old versions, but 2.15 is more than 5 years old, so I haven't used it for a long time...

**Comment by my-name-iz-ayush** [comment]
I'm having issue while 3D meshing any microstructure. Code entered is:
neper -M Polyctrystal_cube.tess -order 2 -meshqualexpr Odis -meshqualmin 1

but i get following as output:

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.6.1-3
Info   : Built with: gsl|muparser|opengjk|nlopt|libscotch
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/root/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] Polyctrystal_cube.tess -order 2 -meshqualexpr Odis
         -meshqualmin 1
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `Polyctrystal_cube.tess'...
Info   :     [i] Parsed file `Polyctrystal_cube.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.131) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing... 100% (0.18|1/37%|32%|31%)
Info   :   - Fixing 2D-mesh pinches...
Info   :   - 3D meshing... Error  : Wrong mesh dimension: -1!
Aborted


can you please help me? thanks in advance

**Comment by rquey** [comment]
Is your Neper installation working (did you run the tests, and did they pass successfully?)?

If so, please provide your tess file.

**Comment by my-name-iz-ayush** [comment]
Tessellation is working properly but it is having issue only while 3D meshing.
Following was my code for tessellation:

neper -T -n 500 -domain "cube(3,3,1)" -o Polycrystal_cube

**Comment by my-name-iz-ayush** [comment]
can you please tell the code to run tests too

**Comment by rquey** [comment]
When you are in Neper's `build` directory (where you compiled), run `ctest`.
https://neper.info/doc/introduction.html#testing-neper

**Comment by my-name-iz-ayush** [comment]
90% tests passed, 44 tests failed out of 460

Total Test time (real) = 245.06 sec

The following tests FAILED:
        129 - M/cl (Failed)
        130 - M/cl_expr (Failed)
        133 - M/clmin (Failed)
        134 - M/clratio (Failed)
        135 - M/cut (Failed)
        136 - M/dim (Failed)
        137 - M/dim2 (Failed)
        138 - M/dim_expr (Failed)
        139 - M/faset (Failed)
        142 - M/interface (Failed)
        143 - M/interface2 (Failed)
        144 - M/interface3 (Failed)
        145 - M/mesh2dalgo_dela (Failed)
        146 - M/mesh2dalgo_fron (Failed)
        147 - M/mesh2dalgo_mead (Failed)
        148 - M/mesh2dalgo_netg (Failed)
        149 - M/mesh3dalgo_netggmne (Failed)
        150 - M/mesh3dalgo_netggmsh (Failed)
        151 - M/mesh3dalgo_netgnetg (Failed)
        152 - M/meshing (Failed)
        154 - M/meshqualdisexpr (Failed)
        155 - M/meshqualexpr (Failed)
        156 - M/meshqualmin (Failed)
        157 - M/morpho_cube (Failed)
        158 - M/nset1 (Failed)
        159 - M/nset2 (Failed)
        160 - M/nset3 (Failed)
        161 - M/order (Failed)
        162 - M/order_dim2 (Failed)
        165 - M/part (Failed)
        166 - M/part2 (Failed)
        167 - M/part_dim2 (Failed)
        168 - M/pl (Failed)
        169 - M/rcl (Failed)
        170 - M/rcl_expr (Failed)
        173 - M/remesh1 (Failed)
        174 - M/remesh2 (Failed)
        175 - M/remesh3 (Failed)
        176 - M/remesh4 (Failed)
        182 - M/statelsetco (Failed)
        188 - M/stateltco (Failed)
        190 - M/tesr_dim2 (Failed)
        193 - M/tess2ddim3 (Failed)
        211 - V/asymptote (Failed)
Errors while running CTest
Output from these tests are in: /mnt/c/Users/Awnish/neper/neper-4.6.0/src/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

**Comment by rquey** [comment]
So, almost all meshing tests.  It must be a Gmsh issue.

**Comment by rquey** [comment]
Install Gmsh, and, more generally, follow the [Installation instructions](https://neper.info/doc/introduction.html#installing-neper).

**Comment by my-name-iz-ayush** [comment]
I followed the Installation Instructions and gmsh is installed using following code in WSL Ubuntu:
sudo apt install gmsh

**Comment by my-name-iz-ayush** [comment]
still error while 3D meshing

**Comment by rquey** [comment]
There was a problem with a recent Gmsh... so, it may be it.

Try to install the latest Gmsh version from the sources, which should solve your issue (take caring of installing Gmsh's own dependencies as well, which show up when you run `cmake ..` during its installation) and will make Neper run much faster too.

**Comment by my-name-iz-ayush** [comment]
Can you please provide source link for latest gmsh version

**Comment by my-name-iz-ayush** [comment]
Thank you, now i'm able to do 3D meshing after installing latest gmsh from source code.
Can you help me with Neper2CAE as its showing abaqus not found but i'm able to use abaqus CAE seperately.

**Comment by ajouslin** [comment]
Hello, I probably have the same problem but I can’t solve it. 
I installed the latest version of gmsh: 4.12.0
But I get as error message :  - Failed to read msh file
Here’s what I get by doing ctest :

93% tests passed, 34 tests failed out of 460

Total Test time (real) =  22.71 sec

The following tests FAILED:
	129 - M/cl (Failed)
	130 - M/cl_expr (Failed)
	133 - M/clmin (Failed)
	134 - M/clratio (Failed)
	135 - M/cut (Failed)
	137 - M/dim2 (Failed)
	138 - M/dim_expr (Failed)
	139 - M/faset (Failed)
	142 - M/interface (Failed)
	143 - M/interface2 (Failed)
	145 - M/mesh2dalgo_dela (Failed)
	146 - M/mesh2dalgo_fron (Failed)
	147 - M/mesh2dalgo_mead (Failed)
	148 - M/mesh2dalgo_netg (Failed)
	149 - M/mesh3dalgo_netggmne (Failed)
	150 - M/mesh3dalgo_netggmsh (Failed)
	151 - M/mesh3dalgo_netgnetg (Failed)
	152 - M/meshing (Failed)
	154 - M/meshqualdisexpr (Failed)
	155 - M/meshqualexpr (Failed)
	156 - M/meshqualmin (Failed)
	157 - M/morpho_cube (Failed)
	158 - M/nset1 (Failed)
	159 - M/nset2 (Failed)
	160 - M/nset3 (Failed)
	161 - M/order (Failed)
	168 - M/pl (Failed)
	169 - M/rcl (Failed)
	170 - M/rcl_expr (Failed)
	173 - M/remesh1 (Failed)
	174 - M/remesh2 (Failed)
	175 - M/remesh3 (Failed)
	182 - M/statelsetco (Failed)
	188 - M/stateltco (Failed)
Errors while running CTest
Output from these tests are in: /home/antoine/Downloads/neper-main/src/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

Thanks in advance
