### ISSUE TITLE
neper -S not work.

### ISSUE THREAD

**Issue by fzw9381** [rquey/neper#147]
I am in the process of learning to use FEPX. When I tried to run example 1, an error occurred.
The neper -S command prompts that the file cannot be read.
<img width="713" alt="捕获" src="https://user-images.githubusercontent.com/56809459/111733840-c759b280-88b3-11eb-9c93-36813900d6d4.PNG">

**Comment by rquey** [comment]
[Duplicate issue](https://github.com/acmelab-ua/FEPX/issues/6) (please don't do this). Closing.
