### ISSUE TITLE
morpho options mutually exclusion and  generating a specified rotated fibre texture

### ISSUE THREAD

**Issue by solerzhuxy** [rquey/neper#15]
1. morpho options mutually exclusion in 'gg' and 'diameq:dirac(0.1'
I tried the -T options like"$NEPER -T -n 240 -domain "cube(1.0,1.0,1.0)" -morpho "gg,diameq:dirac(0.1)" -reg 1 -ori random -o n240". The result grain size distribution seem more uniform than use "-morpho  "diameq:dirac(0.1), sphericity(0.145,0.03,1-x)" " or " -morpho "gg" -reg 1" only.  
‘gg’ and ‘diameq:dirac(0.1)’ can play a certain role in morpho controlling, but the mechanism is not clear.
2. A fibre texture can be defined using -ori 'fibre('z',0,0,1)', or 'e(0,40,0) for rotation. If a intermediate   rotation operation following the initial texture configuration 'fibre('z',0,0,1)', executing 'fibre('z',0,0,1),e(0,40,0)' will prove that these two options are mutually exclusion. Only the first options fibre() or e() will be active. But if a intermediate roation configuration  set as a target, is it possible for Neper to generate?

**Comment by rquey** [comment]
1. A single properiy (like `diameq`) may indeed be given several arguments, which can, in some cases, be useful. In the case mentioned above, the two arguments contradict, which will lead to an unexpected behaviour --- the result will certainly **not** be more uniform than "diameq:dirac(0.1), sphericity(0.145,0.03,1-x)".
2. A fix for `-ori fibre` will be provided soon, which will solve this issue.
