### ISSUE TITLE
2D RVE offset

### ISSUE THREAD

**Issue by Hx83866** [rquey/neper#157]
Hello Everyone,

**Is there any method to generate a 2.5D RVE by offsetting a 2D RVE?**

What I have generated is a pseudo-2.5D RVE by setting a small thickness of a 3D RVE.
![sheet_04](https://user-images.githubusercontent.com/35709665/112304827-3c572e80-8c9e-11eb-9e2b-f7e801641bf3.png)

However, it doesn't work with the CP subroutines given by my institute.

Best Regards,
Xiang Hu

**Comment by rquey** [comment]
Yes. If you are aiming to a mesh, the simplest way is to generate a 2D tessellation and to enforce 3D meshing.  Here is an example:

```
$ neper -T -n 2::2 -dim 2 -o test
$ neper -M test.tess -dim 3
$ neper -V test.tess,tess.msh -dataelsetcol id -print test
```

![image](https://user-images.githubusercontent.com/2659376/112309194-59dac700-8ca3-11eb-8600-b01f4a819fe6.png)

**Comment by Hx83866** [comment]
Cool! 
Can I give a command, such as 
`$ neper -M test.tess -dim 3 -cl 1.0`
to control the the thickness?

**Comment by rquey** [comment]
The thickness is equal to one element size. It cannot be controlled right now...

```
$ neper -M test.tess -dim 3 -rcl 0.5
$ neper -V test.tess,tess.msh -dataelsetcol id -print test
```

![image](https://user-images.githubusercontent.com/2659376/112312676-59442f80-8ca7-11eb-839c-09b5a16ecdd3.png)

**Comment by Hx83866** [comment]
If the required thickness is exactly equal to one single element size, then this method is pretty perfect.

Thank you very much. It helps me a lot. I will close the issue.

**Comment by 123fgh123** [comment]
> The thickness is equal to one element size. It cannot be controlled right now...
> 
> ```
> $ neper -M test.tess -dim 3 -rcl 0.5
> $ neper -V test.tess,tess.msh -dataelsetcol id -print test
> ```
> 
> ![image](https://user-images.githubusercontent.com/2659376/112312676-59442f80-8ca7-11eb-839c-09b5a16ecdd3.png)

Is it possible to mesh it with hex element? I had tried but no .msh file was generated.

$ neper -M test.tess -dim 3 -elttype hex -o test-hex
