### ISSUE TITLE
Cell merging fails

### ISSUE THREAD

**Issue by Hx83866** [rquey/neper#158]
Hello Everyone,

I got a bug while I was trying to merge cells whose eqv. diameters were small. 
Here are my code:
`$neper -T -n ...... -dim 2 -transform "mergecell(diameq<=0.1), resetcellid" .....`

However, the software terminated itself while merging cells and reported a bug:
```
......
Info   :   [level] Flattening 3-scale tessellation...
Info   :   [    2]  3/3: id=4
Info   :   [    1]  1/1: id=1
Info   : Transforming tessellation...
Info   :   - Merging cells...
Info   :     [o] Writing file `tess.debug'...
face = 202
edges = 454 461 612 648 649 1127
Info   :     [o] Wrote file `tess.debug'.
Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

Aborted
```

What I want to do is to eliminate mesh difficulties in some extremely narrow cells, see in the figure below:

![Inkedsheet_05_LI](https://user-images.githubusercontent.com/35709665/112348891-894ffa80-8cc8-11eb-89c9-4df2f1b644f3.jpg)

Or could you pls give me some good advice to obtain a high quality mesh?

Best Regards,
Xiang Hu

**Comment by rquey** [comment]
It does not work because you are trying to merge all cells that match the criterion _together_, but these the cells are not _adjacent_.

Did you use regularization? It should solve some of the issues.

Another workaround would be to improve the positioning of the lamellae.  I'll try to have a look at it in the next days.

Next time, please provide your full Neper command, as it makes it possible to reproduce your example.

**Comment by Hx83866** [comment]
> Did you use regularization? It should solve some of the issues.

Yep, the regularization did help me with some issues. 

> It does not work because you are trying to merge all cells that match the criterion together, but these the cells are not adjacent.

I see. but which arguments could help to judge the adjacent relationship and merge the narrow lamella with the adjacent cell?

**Comment by rquey** [comment]
I don't think that this operation can be written simply as a `mergecell` argument.

**Comment by rquey** [comment]
This can be fixed using `lamellar(...,pos=optimal)`.
