### ISSUE TITLE
shared_libraries

### ISSUE THREAD

**Issue by ewpostek** [rquey/neper#16]
Dear Colleagues,
How to get rid of the error ?

ewpostek@tryton-ap:/users/work/ewpostek/neper/neper-devel/install/bin$ ./neper
./neper: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory 

I extended the env variable to point out the directory with libgsl.so.23 but it did not work.

best,
Elek

**Comment by rquey** [comment]
How did you install the GSL?  Did Neper find it when running `cmake ..`?

**Comment by ewpostek** [comment]
Yes, neper has found it whe running cmake
Neper was installed.
I set the path whe running cmake 
manually -DGSL_CONFIG:FILEPATH=/users/work/ewpostek/neper/gsl25a/gsl/bin/gsl-config

Next, I simply should add the gsl libraries path to the env variable LD_LIBRARY_PATH,
not to PATH.
It works after the modification,
Elek
