### ISSUE TITLE
Fix regularization of general 2D tessellation

### ISSUE THREAD

**Issue by rquey** [rquey/neper#18]
In the case of a 2D tessellation, regularization assumes that the tessellation is in the x-y plane.  However, option `-transform slice` may generate 2D tessellations which are not in the x-y plane.  Regularization should therefore be generalized.

Here is the guilty code, `net_reg_merge_del3.c line 298`:
```
ut_space_points_line ((*pTess).DomVerCoo[domver1], (*pTess).DomVerCoo[domver2], eqs[i]);                        
```

**Comment by prsdshiva** [comment]
Thank you Romain for fixing this issue :100:
