### ISSUE TITLE
Coarsening polycrystal mesh while maintaining number of grains

### ISSUE THREAD

**Issue by pawanchaugule** [rquey/neper#201]
Hello,

I created a cubic tesselation representing a polycrystal containing 625 grains using the below command:
neper -T -n 625 -domain "cube(5,5,5)" -morpho gg -statcell size -o 625grains_gg_dist -oridescriptor e -regularization 1 -oriformat geof 
 
I then meshed the tesselation with hexagonal elements using the following command:
neper -M 625grains_gg_dist.tess -elttype hex -order 1 -rcl 1 -o 625grains_gg_dist -format geof

I wish to do a mesh analysis study, so I tried producing a coarser mesh by increasing the -rcl from 1 to 2. It resulted in a coarser mesh but some of the elsets were not assigned and remained empty. This meant the polycrystal actually reduced in terms of number of grains. _**_I would like to know a way in which I can preserve the number of grains  (625) and produce a coarse mesh, or basically a mesh file with a smaller size (memory)?_**_

I have tried using command -meshqualmin with various values from 0 to 1 but it didn't seem to do the trick. 

P.S. - Please feel free to suggest any edits to the above-mentioed commands to get a better mesh.
 
Let me know if you have any questions about my issue.

Thank you to Romain Quey for answering my previous question and the questions on the forum.

**Comment by rquey** [comment]
This is inevitable with hex meshing, when the number of elements is getting low. Some grains may not receive any element. The number of elements may even be smaller than the number of grains.

As for your command, you do not need to use regularization with hex meshing, and `-meshqualmin` has no effect for hex meshing.
