### ISSUE TITLE
outputting problem when domain dim set to 2

### ISSUE THREAD

**Issue by xajezade** [rquey/neper#21]
Hello there;
Here is an example:

neper -T -dim 2 -id 1 -domain "square(64,64)" -n from_morpho -morpho "diameq:lognormal(4.29,4),1-sphericity:lognormal(0.145,0.03)" -tesrsize 256:256 -statcell modeid -o scale1 -format tess,tesr,vtk

it doesn't produce a *.tesr file. it doesn't produce a *.vtk file. the stcell file is also empty.
3D version is fine.

Regards,
Ali

**Comment by rquey** [comment]
Better a MWE: `neper -T -n 1 -dim 2 -for tess,tesr -statcell modeid`
