### ISSUE TITLE
Issue with increasing number of grains

### ISSUE THREAD

**Issue by Shahrzad1989** [rquey/neper#221]
Hi all. I am trying to make 3D RVEs applying periodicity and then I import the geometry in Abaqus. For 100 grains, I didn't face a problem but when I increase the number of grains, some geometrical aspects in .tess is missing which results in problem with exporting to Abaqus. I use this command
neper -T -n 200 -morpho graingrowth -periodicity all
Could you let me know how I can solve this problem?

**Comment by rquey** [comment]
The tess seems to be perfectly fine for me (using the last version). Same for the mesh.
![image](https://user-images.githubusercontent.com/2659376/119687667-ada29180-be47-11eb-8cee-dba76d70bf4c.png)
![image](https://user-images.githubusercontent.com/2659376/119688006-eb9fb580-be47-11eb-84eb-94752a6f47e2.png)
