### ISSUE TITLE
Installation issue with Neper version > 4.0

### ISSUE THREAD

**Issue by dikshanshs** [rquey/neper#234]
![image](https://user-images.githubusercontent.com/85054451/120096837-43d9fe80-c14b-11eb-90cb-053c62bacf65.png)

**Comment by rquey** [comment]
Please use a recent Neper version and provide a complete bug report (including all inputs). Provide the Neper output preferably using copy/paste, i.e. as _text_ and not as a screenshot.

(You can edit your original message.)

**Comment by dikshanshs** [comment]
Actually, there was a problem in installing neper-4.1.2 that is why I was working with neper-4.0.0

While installing Neper-4.1.2 it was showing the following please help me fix this issue.

![image](https://user-images.githubusercontent.com/85054451/120362650-eac7c180-c328-11eb-8e4f-7c5978ca9867.png)

**Comment by rquey** [comment]
What is your system? What is your CMake version?

**Comment by dikshanshs** [comment]
System Information
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
8GB|1TB
Windows 10 Home

CMake version 3.20.2

**Comment by dikshanshs** [comment]
> Actually, there was a problem in installing neper-4.1.2 that is why I was working with neper-4.0.0
> 
> While installing Neper-4.1.2 it was showing the following please help me fix this issue.
> 
> ![image](https://user-images.githubusercontent.com/85054451/120362650-eac7c180-c328-11eb-8e4f-7c5978ca9867.png)


Finally, the Current version installed using a .zip file rather than .tar.gz.
