### ISSUE TITLE
Nine-noded quadrilateral (Q9) element

### ISSUE THREAD

**Issue by biomech7** [rquey/neper#24]
In my interests, the plane nine-noded quadrilateral (Q9) element usually used for incompressible hyperelastic materials using Voronoi tessellation. I wonder if you could add the quad element in the second-order finite element library.

**Comment by rquey** [comment]
@biomech7 Almost done. It works in `msh` format. What format are you needing?

**Comment by biomech7** [comment]
Dear Dr. Quey:
I would appreciate it if you could add Abaqus ‘.inp’ and the Gmsh ‘.msh’. 
Thank you. 
​
-----Original Message-----

**Comment by rquey** [comment]
Can you provide the element details for abaqus?  Element name and node sequence (does the central node come last?)

**Comment by biomech7** [comment]
Dear Dr. Quey:
 
I checked the finte element library of abaqus. But there is no 9-noded quadrilateral element. 8-node like CPE8 (plane strain element) is the highest 2nd order element.  
So I need to make user element subroutine(UEL) for Q9 element. I wonder if you could name the element CPE9 for abaqus format. It is just for temporary name of the element.
After that I can use the nodes and finite element sequence in a complex shape. The node numbering is shown in below figure as a reference.
Yes. The center node is the last. Thank you.
     
 
  
-----Original Message-----
