### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dikshanshs** [rquey/neper#246]
Hi @rquey,
Here is a bug
Syntax used
**$neper -T -n 210 -morphooptiini "coo:file(casts.txt)" -domain "square(128,128)" -dim 2 -o casts**
coo file : [casts.txt](https://github.com/rquey/neper/files/6643482/casts.txt)

![image](https://user-images.githubusercontent.com/85054451/121799329-1b70fa80-cc49-11eb-93de-292ee9c5d706.png)

**Comment by rquey** [comment]
Randomize the coordinates, and it will work:
```
$ gsl-randist 1 210 flat 0 0.001 > x
$ gsl-randist 2 210 flat 0 0.001 > y
$ paste x y casts.txt | awk '{print $1+$3,$2+$4}' > casts.txt2
$ neper -T -n 210 -morphooptiini "coo:file(casts2.txt)" -domain "square(128,128)" -dim 2 -o casts
```
