### ISSUE TITLE
Can neper plot the crystal orientation distribution?

### ISSUE THREAD

**Issue by fzw9381** [rquey/neper#249]
Can neper plot the crystal orientation distribution? 
I saw the distribution map of the crystal orientation on the official website. Is that one generated by neper?

**Comment by CsatiZoltan** [comment]
Yes, it can. If the orientations are given in your mesh file within the
```
$ElsetOrientations
...
$EndElsetOrientations
```
section, you can colour the element sets based on the crystal orientations by using
```
neper -V your_mesh.msh -dataelset3dcol ori -print output
```
Check Section 5.1.5 in the [manual](https://neper.info/docs/neper.pdf).

**Comment by mkasemer** [comment]
Perhaps @fzw9381 is referring to "orientation distributions" for example on pole figures (fiber distributions), rather than spatial distributions of orientations plotted on the FE mesh?

**Comment by yguilhem** [comment]
That might have been generated using [mtex](https://mtex-toolbox.github.io/) (matlab toolbox) or something similar.

**Comment by rquey** [comment]
Pole figures (and other orientation figures) are plotted using an in-house code. That in-house code generates top-quality figures in vectorial format (with Latex fonts). Something I can push to Neper in the mid term if there is interest.
