### ISSUE TITLE
optimization fails for multiscale big microstructures

### ISSUE THREAD

**Issue by xajezade** [rquey/neper#25]
Hi there;
here is an example:
Step1: 
```
neper -T -dim 2 -domain "square(300,300)" -n from_morpho -morpho "diameq:0.34*lognormal(4.29,4,from=1.)+0.66*lognormal(7.11,13.9,from=1.),diameq:interval(1,20),sphericity:lognormal(0.001,0.01,1-x)" -tesrsize 512:512 -statcell modeid -o scale1 -format tess,tesr,vtk
```
Step 2:
```
awk '{if ($1==1) {print NR,"diameq:lognormal(2.05,0.75,from=0.5),diameq:interval(0.5,5),1-sphericity:lognormal(0.145,0.03)"} else {print NR,"diameq:lognormal(1.78,0.7,from=0.5),diameq:interval(0.5,5),1-sphericity:lognormal(0.145,0.03)"}}' scale1.stcell > scale2-morph
```
Step 3:
```
neper -T -n 425 -domain "cube(300,300,300)" -morphooptiini "coo:msfile(scale1.tess),weight:msfile(scale1.tess)" -morpho "columnar(z)" -tesrsize 512:512:512 -o scale1-3D -format tess,tesr,vtk
```
Step 4:
```
neper -T -id 1::2 -domain "cube(300,300,300)" -n from_morpho::from_morpho -morpho "msfile(scale1-3D.tess)::msfile(scale2-morpho)" -morphooptialgo "subplex::subplex" -morphooptistop "itermax=7000::itermax=7000" -tesrsize 1024:1024:1024 -o scale2 -tesrformat "ascii" -format tess,tesr,vtk
```

The final step stops with a bug report error (. if the "itermax" parameter is increased, sometimes it goes further with tesselation but stops again with the same error. I have noticed that the final solution is a very big number while fmin is a small value.  
example of the tail of my Slurm file:
```
teration   6993: fmin=0.039809048 f=6196.709123290
Iteration   6994: fmin=0.039809048 f=5650.356232039
Iteration   6995: fmin=0.039809048 f=4649.825485562
Iteration   6996: fmin=0.039809048 f=5946.673046066
Iteration   6997: fmin=0.039809048 f=4649.825568279
Iteration   6998: fmin=0.039809048 f=4649.825661488
Iteration   6999: fmin=0.039809048 f=4649.825373768
Iteration   7000: fmin=0.039809048 f=4649.826241255
Info   :     > 
Final   solution: f   =7608.280592484
Info   :     > Reached `itermax' criterion.
number of common seeds = 4 != 3
seeds = 304 761 -6 149
Error  : You have discovered a bug in Neper!  Please send a full bug
         report to <rquey@users.sf.net>.  Thank you.
```

Thanks,

Ali

**Comment by xajezade** [comment]
Hi Romain;
If you check, only subplex and neldermead algorithms work, the others fail to begin (check praxis for example). I have noticed the sublex fails when I have a small volume for scale 1! That's why I have removed small grains at scale 1.  

Thanks,
Ali

**Comment by rquey** [comment]
To begin with, your step 1 should be:
```
$ neper -T -dim 2 -domain "square(300,300)" -n from_morpho -morpho "diameq:0.34*lognormal(4.29,4,from=1.)+0.66*lognormal(7.11,13.9,from=1.),diameq:interval(1,20),1-sphericity:lognormal(0.1,0.01)" -tesrsize 512:512 -statcell modeid -o scale1 -format tess,tesr,vtk
```
i.e. the sphericity average should not be above ~0.9 (so, not below 0.1 for 1-sphericity). A hexagon has a sphericity (or "circularity") of 0.907, so a higher average value will be difficult to get.  With a more sound value, optimization will be easier (and a larger standard deviation, such as the default 0.03, would also help).

As for Praxis, it needs a memory in n²+ 9*n.  For numbers of cells above a few thousands, this becomes a huge number and the program dies before even starting to optimize.  This is what you are experiencing.  It is probably the same for all others but Subplex (and neldermead, as you mentioned). Actually, only Subplex and Praxis are efficient in `-morpho`, and only Subplex supports large numbers of cells.

**Comment by wz116529385** [comment]
Hi, xajezade；
 when i run the 4th step of your code "neper -T -id 1::2 -domain "cube(300,300,300)" -n from_morpho::from_morpho -morpho "msfile(scale1-3D.tess)::msfile(scale2-morpho)" -morphooptialgo "subplex::subplex" -morphooptistop "itermax=7000::itermax=7000" -tesrsize 1024:1024:1024 -o scale2 -tesrformat "ascii" -format tess,tesr,vtk", it was stopped  with a "Segmentation fault (core dumped)", do you had a similar problem, and how to deal with it?
 You answer will be appreciated.
  Wang
![图片](https://user-images.githubusercontent.com/69336123/89856278-6b1b0b80-dbcb-11ea-9e4f-aedffa002387.png)

**Comment by xajezade** [comment]
Hi Wang,

I am having the same problem with the new version of the code. I want to retry with the previous versions to see if it resolves the problem.

I’ll let you know about it. 

Kindest Regards,

Ali

**Comment by rquey** [comment]
Please provide the actual series of commands, so I can have a look at it.

**Comment by wz116529385** [comment]
> 
> 
> Please provide the actual series of commands, so I can have a look at it.

Hi,Romain, here is the commands and original node file. Thanks again.
Sincerely appreciate.
Wang
`gsl-randist 1 6417 flat 0 0.000001 > x
gsl-randist 2 6417 flat 0 0.000001 > y
gsl-randist 3 6417 flat 0 0.000001 > z
paste node2.txt x y z | awk '{print $1+$4,$2+$5,$3+$6}' > pos2
neper -T -n 6417 -domain 'cylinder(0.1,0.05)' -morphooptiini "coo:file(pos2)"  -reg 1 -o n11
neper -V n11.tess -datacellcol id -imagesize 900:450 -print img1
neper -T -n from_morpho::5 -morpho 'file(n11.tess)::diameq:dirac(1),1-sphericity:lognormal(0.145,0.03)' -o mult_11 -format tess,3dec`
[node2.txt](https://github.com/rquey/neper/files/5090542/node2.txt)

**Comment by rquey** [comment]
Don't regularize a tessellation before loading it in `-morpho 'file()'` to generate a 2nd scale onto it - It won't work.

**Comment by wz116529385** [comment]
Hi，Romain
   I ran the following commads according to your suggestion, but it didn't work out yet. Note that the code  version used is 3.5.2. For rigth now the "neper.info"  cann't be open, and the newest version cann't be loaded.
Best Regards
Wang
 `neper -T -n 6417 -domain 'cube(0.06,0.06,0.11)' -morphooptiini "coo:file(pos2)"  -o n11` 
 `neper -T -domain 'cylinder(0.1,0.05,100)' -n from_morpho::5 -morpho 'file(n11.tess)::centroidal' -o mult_11 -format tess,3dec`

**Comment by xajezade** [comment]
Hi Wang,

Check the following:
https://github.com/rquey/neper <https://github.com/rquey/neper>

Regards,
Ali

**Comment by wz116529385** [comment]
Thanks, Ali. It's very kind of you.
