### ISSUE TITLE
Issues with generating wider grain size distribution

### ISSUE THREAD

**Issue by prsdshiva** [rquey/neper#26]
I have been trying to generation 2D tesselation for wider grain size distribution ( both normal and lognormal distributions)

Code used: 
`neper -T -n from_morpho -id 1 -dim 2 -domain "square(60,10)" -morpho "diameq:lognormal(0.285,0.226),sphericity:lognormal(0.145,0.03,1-sphericity)" -statcell diameq,circularity -o Grain_2D-format ply,tess`

Version neper 3.5.0

I have tried three cases. The input  & output mean/standard deviation values are shown herewith. (All-grain values in microns.)

Case 1: Log normal distribution 
 Input grain values : mean = 285 & Std=226 |  Output : mean 338 & std=130

Case 2: Log normal distribution 
 Input grain values : mean = 285 & Std=86 |  Output: mean 276 & std=107

Case 3: Normal distribution 
Input grain values : mean = 285 & Std=226 |  Output mean 337 & std=137

Can we obtain closer agreements with the input values for wider size distribution cases?

**Comment by rquey** [comment]
Thanks @prsdshiva for insisting on this bug. It was incredibly simple to fix once in the right place (f45f28b). I wish I had seen this before... You will see that optimization now runs very smoothly for your examples.
