### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nizhiyang-debug** [rquey/neper#284]
how can l generate grain structure like this sir?
![](https://user-images.githubusercontent.com/81605789/129671899-5a21508b-69c2-4253-94cf-77bd11b683b0.png)

**Comment by nizhiyang-debug** [comment]
![neper](https://user-images.githubusercontent.com/81605789/129671899-5a21508b-69c2-4253-94cf-77bd11b683b0.png)

**Comment by rquey** [comment]
Neper does not generate matrix/inclusions structures such as this one.
