### ISSUE TITLE
Meshing Module -rcledge

### ISSUE THREAD

**Issue by akshat04216** [rquey/neper#29]
Hello,

I'm trying to get this simple code to finely mesh only one edge of a square domain but I dont know where I am going wrong. 

neper -M nfrom_morpho-id161.tess -elttype 'tet' -order 1 -interface 'cohesive' -format 'inp','msh' -rcledge '(domedge==1)?val:0.25'

Any help will be appreciated in rectifying the issue, Thanks!

**Comment by rquey** [comment]
Please provide a MWE including all the data necessary to reproduce the bug (Neper's terminal output helps, too).

**Comment by akshat04216** [comment]
Thank you for the quick reply. Mentioned below are all the details.

neper -T -n from_morpho -id 161 -domain "square(0.200,0.100)" -transform "translate(-0.100,-0.100,0)" -morpho "diameq:normal(0.01,0.00001)" -morphooptistop 'itermax=15000' -reg 1 -dim 2 -format 'tess','geo','ply' -statcell diameq

neper -M nfrom_morpho-id161.tess -elttype 'tet' -order 1 -interface 'cohesive' -format 'inp','msh' -rcledge '(domedge==1)?val:0.25'

Neper's Terminal Output:
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] nfrom_morpho-id161.tess -elttype tet -order 1
         -interface cohesive -format inp,msh -rcledge
         (domedge==1)?val:0.25
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `nfrom_morpho-id161.tess'...
Info   :     [i] Parsed file `nfrom_morpho-id161.tess'.
Info   : Meshing...
Info   :   - Preparing... /usr/local/bin/neper: line 12: 26100 Aborted                 (core dumped) ${INSTALL_DIR}/bin/neper.bin $*

**Comment by rquey** [comment]
It just does not know what `val` is. Replace it by a numeral.
