### ISSUE TITLE
regularization for sphere

### ISSUE THREAD

**Issue by xinhe2205** [rquey/neper#32]
I am trying to regularization the 3D Voronoi diagram bounded by a sphere using `neper -T -n 50 -domain "sphere(500, 50)" -format ply -reg 1`, it through an error saying there is a bug.

**Comment by rquey** [comment]
Regularization in a spherical domain does not work as smoothly as on e.g. a cubic domain.  A workaround is to decrease the value of `-rsel` (default 1) to make regularization stop earlier.

In your case, you can safely decrease `-rsel` to e.g. 0.5 (and then, in -M, divide the default value of `-pl` by 0.5 to avoid local mesh overrefinement; so, use `-pl 4`).

**Comment by xinhe2205** [comment]
Thank you for your reply. I will give it  a try.
