### ISSUE TITLE
precision of the coordinate of vertices

### ISSUE THREAD

**Issue by xinhe2205** [rquey/neper#33]
I am wondering if there is a way to change the precision of the coordinates of vertices. By default, there are 12 digits after decimal, when I import the geometry to Abaqus (points to wires to faces to volume), it can not create face as it can only include 6 digits after the decimal. I am wondering if there is a way to change the default precision of coordinates in Neper. 

Thank you.

**Comment by rquey** [comment]
Do you mean in the `.tess` file?

**Comment by xinhe2205** [comment]
Yes.

[Xin He - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=bonp0)	[bonp0]

On January 6, 2020 at 20:22 GMT, Romain Quey <notifications@github.com> wrote:

Do you mean in the .tess file?

**Comment by rquey** [comment]
To make things clear, are you really loading a `.tess` directly in Abaqus? If yes, how is this possible?

**Comment by xinhe2205** [comment]
No, it is not a direct loading. I created polygons then forming surfaces volumes in Abaqus by python scripting.

**Comment by xinhe2205** [comment]
No. It is not a direct loading. I developed the Python scripting to read the data from .ply file and create polygons, surfaces, then volume in Abaqus.

**Comment by rquey** [comment]
So, you need the `.ply` file to be formatted with fewer digits? Can't you manage formatting issues through your Python?

**Comment by xinhe2205** [comment]
Yes, I want the .ply to be formatted with fewer digits. Abaqus can only read 6 digits after decimal. I cannot change this default setting in Abaqus through Python. The thing I can do is to reformat the .ply file, but this would be challenge as I need make sure all vertices on the same surface keep on the same surface after reformatting. This would be challenge.

**Comment by rquey** [comment]
This is quite specific, so I am a bit reluctant about adding it to Neper.
Here is how you can reformat a `ply` file in Bash:
```
file=n20-id1.ply
awk -v qty=`sed -n "3,3p" $file | awk '{print $3}'` '{if (NR<12||NR>=12+qty) {print} else {printf "%.6f %.6f %.6f\n", $1,$2,$3}}' $file
```
