### ISSUE TITLE
Neper doesn't find GMSH

### ISSUE THREAD

**Issue by 5A5H** [rquey/neper#351]
Hey guys,
I'm having trouble to run meshing in neper.
The Output, e.g. for `./neper -M` says:
```
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.2.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 8 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2021, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/sash/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] (none)
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
4.9.1
Error  :     > Option `-gmsh' does not provide a valid path to the gmsh binary.
Aborted (core dumped)
```
Gmsh is build from source, installed and runs fine:
`echo $(which gmsh) $(gmsh --version)` => `/home/sash/local/bin/gmsh 4.9.1`

Other than for meshing, neper passes all test.
I have tried starting neper with pointing to the Gmsh executable `./neper -M -gmsh $(which gmsh)`
which causes the same error.
Any Ideas what's the problem here ?
Thanks in advance!

**Comment by rquey** [comment]
This was due to a change in Gmsh. Thanks @5A5H for the bug report!

Fixed in version 4.2.1-20.

**Comment by 5A5H** [comment]
Thank you!!

**Comment by Maohua10** [comment]
> This was due to a change in Gmsh. Thanks @5A5H for the bug report!
> 
> Fixed in version 4.2.1-20.

Hi Dr. Quey, the same problem occured to me as I got the version 4.1.2 installed. 

Since I am running the program using windows, this is the latest version that I can get from anaconda. I had several other environment issues installing the latest version.

Any ideas how I can fix the change in Gmsh problem with this old version? 

Thank you very much,
Maohua

**Comment by rquey** [comment]
What is your Neper version? Is Gmsh available at the command line, as `gmsh`? Did you run Neper's tests?

**Comment by surendranlu** [comment]
gmsh is available in command line.  My gmsh version is 4.12.1, Neper is 4.10.2-6. I am using ubuntu. Gmsh runs from command line. Both view module (-V) and mesh module (-M) do not work.
