### ISSUE TITLE
Import user-defined data obtained from EBSD

### ISSUE THREAD

**Issue by preethamalluri** [rquey/neper#36]
Bonjour Prof. Romain,

Firstly, I am very grateful to you for providing this free open software neper. I am trying to generate polycrystal mesh with neper and the results are really great. However, I have the following question. Can you please go through it and answer me if this is possible? 

Q.1 >How to import user-defined data (grain morphology, grain size distribution, and orientation(texture)) which is obtained from experimentally measured EBSD in Neper?
I think I am able to generate the user defined crystal orientation data using the Crystal orientation options, _"ori"_.
_‘file(filename):des’_ for reading orientations from file filename.
For generation using the euler angles bunge convention, I simply define the "e" in the place of 'des'?

Merci beaucoup :)

Bien cordialement
Preetham Alluri

Experimental data 

259.493184        90.217113       213.733597       
84.690105         104.440721      299.908358    
261.563114        95.106324       140.132003        
92.566247          88.191844       223.654815 
260.951927        95.979226       226.056886
12.792870         132.007337     189.317481 
169.278815       58.322459       182.482430 
168.578867       127.845071     269.745798 
110.568289       87.518977       293.056839 
190.629753      146.474133      98.601316

![image](https://user-images.githubusercontent.com/23463429/72707299-6fd29080-3ba3-11ea-951a-3ab00e2f665d.png)

**Comment by rquey** [comment]
Sorry for the late response, but:
- grain morphology can be specified using `-morpho`; see the paper "Optimal descrption..." for what is possible (from the Downloads section of the website) and the examples of the manual or website to see how it works.
- grain orientation can be specified using `-ori`.You are correct about the format. The default is Euler angles in Bunge convention, so you can simply use `-ori "file(filename)"`.
