### ISSUE TITLE
[FEpX] Loading a .msh file to repartition results in reordering of face set

### ISSUE THREAD

**Issue by jcappola** [rquey/neper#37]
When generated a mesh file for FEpX from the same tessellation it seems that partitioning during the original meshing module call versus loading an unpartitioned .msh file and outputting a partitioned file results in reordering of the printed faset.

This bug report is occurring in Neper-3.4.0. The following commands can reproduce the error:

`neper -T -n 50 -id 1 -reg 1 -mloop 4 -format tess -domain "cube(1,1,1)"`

Next, produce a 'serial' mesh output in FEpX format (i.e. no partition):

`neper -M n50-id1.tess -order 2 -o n50-id1 -format fepx,msh -faset z0,z1,x0,x1,y0,y1`

Now, we produce a mesh that is partitioned at run time (1) and one that is loaded into Neper from the above 'serial' mesh and partitioned (2):

(1) `neper -M n50-id1.tess -order 2 -o n50-id1 -format fepx,msh -faset z0,z1,x0,x1,y0,y1 -part 1:4`

(2) `neper -M -loadmesh n50-id1.msh -part 1:4 -format fepx,msh -faset z0,z1,x0,x1,y0,y1`

For example, this results in the following typical reordering in the faset for the resulting FEpX mesh. Shown are is the first line of the z0 face set after the declaration of the number of surfaces and the number of elements with a face on the z0 surface:

Partitioned at run-time:
1774 2714 **3106 2716** 3107 **2768 3108** 

Partitioned after loading serial mesh:
1774 2714 **3108 2768** 3107 **2716 3106** 

Above reordered node numbers are bolded for clarity. I'm unsure of the cause of this reordering, but it seems to indirectly be the cause of a sign change on surface normal calculation internal to FEpX and results in flipped signs on reported target surface loads.

**Comment by rquey** [comment]
Debugging script (along the same lines as above):
```
#!/bin/bash

# generating tessellation
./neper -T -n 50 -id 1 -reg 1

#generating serial mesh
./neper -M n50-id1.tess -format fepx,msh -order 2 -faset z0,z1,x0,x1,y0,y1 -o serial

# generating partitioned mesh
./neper -M n50-id1.tess -format fepx,msh -order 2 -part 1:4 -faset z0,z1,x0,x1,y0,y1 -o part1

# generating partitioned mesh with reloading
./neper -M n50-id1.tess -loadmesh serial.msh -format fepx,msh -order 2 -part 1:4 -faset z0,z1,x0,x1,y0,y1 -o part2

# testing
diff part1.msh part2.msh
diff part1.mesh part2.mesh

exit 0
```
