### ISSUE TITLE
Bug with conversion of .tesr to .msh

### ISSUE THREAD

**Issue by BjarkeOestergaard** [rquey/neper#387]
**Describtion of bug**

When a non cubic geometry is used for the .tesr, it forces the entire shape to be cubic when using the meshing module, thus changing the dimensions of each element. 

**To Reproduce**

the .tesr file (test.tesr) is: 

```
***tesr 
 **format 
   2.0 ascii 
 **general 
   3 
   2 2 3
   1.0 1.0 1.0
 **cell
   1
  *ori 
   ek
   123.752     38.990    230.926 
 **data 
   1 1 1 1 1 1 1 1 1 1 1 1
 ***end 
```

Where it is a (2,2,3) geometry, when converting it to a mesh with:

```
neper -M test.tesr -elttype hex -rcl 2  -format msh -o test
```

I have tested this on different .ters datasets, where i have boiled my problem down to this. 

**Showcase**

To avoid any confusion, i have shown the problem here. 
![Bug-tesr-2-msh](https://user-images.githubusercontent.com/97598804/154051472-d1351bce-af71-4579-b045-e8f606b4bb9a.png)

And the reason it is a problem, is because i have a rod in .tesr format from an experiment, which gets squashed down when translated to .msh (more precisely as .inp) as shown below

![Bug2](https://user-images.githubusercontent.com/97598804/154052139-1bc6580d-863e-4e85-b0aa-aaf595d38a98.png)

**Comment by rquey** [comment]
Thanks @BjarkeOestergaard for the bug report. This is now fixed.
