### ISSUE TITLE
Cannot install the neper version 4.4.0 properly

### ISSUE THREAD

**Issue by fzw9381** [rquey/neper#405]
When I installed neper and tried to make test, some parts failed.

89% tests passed, 35 tests failed out of 307

Total Test time (real) = 259.42 sec

The following tests FAILED:
	114 - M/cl (Failed)
	115 - M/cl_expr (Failed)
	118 - M/clmin (Failed)
	119 - M/clratio (Failed)
	120 - M/dim (Failed)
	121 - M/dim2 (Failed)
	122 - M/dim_expr (Failed)
	123 - M/faset (Failed)
	126 - M/interface (Failed)
	127 - M/interface2 (Failed)
	128 - M/interface3 (Failed)
	129 - M/mesh2dalgo_dela (Failed)
	130 - M/mesh2dalgo_fron (Failed)
	131 - M/mesh2dalgo_mead (Failed)
	132 - M/mesh2dalgo_netg (Failed)
	133 - M/mesh3dalgo_netggmne (Failed)
	134 - M/mesh3dalgo_netggmsh (Failed)
	135 - M/mesh3dalgo_netgnetg (Failed)
	136 - M/meshing (Failed)
	138 - M/meshqualdisexpr (Failed)
	139 - M/meshqualexpr (Failed)
	140 - M/meshqualmin (Failed)
	141 - M/nset1 (Failed)
	142 - M/nset2 (Failed)
	143 - M/nset3 (Failed)
	144 - M/order (Failed)
	145 - M/order_dim2 (Failed)
	150 - M/part_dim2 (Failed)
	151 - M/pl (Failed)
	152 - M/rcl (Failed)
	153 - M/rcl_expr (Failed)
	156 - M/remesh1 (Failed)
	157 - M/remesh2 (Failed)
	158 - M/remesh3 (Failed)
	170 - M/tesr_dim2 (Failed)
Errors while running CTest
make: *** [Makefile:107：test] Error 8

cpfem@cpfem:~/neper-4.4.0/src/build$ sudo make install
[ 26%] Built target scotch
[ 31%] Built target nlopt
[ 31%] Built target scotcherrexit
[ 31%] Built target scotcherr
[ 32%] Built target muparser
[ 36%] Built target orilib
[ 37%] Built target openGJKlib
[ 41%] Built target ut
[ 61%] Built target neper_t
[ 80%] Built target neut
[ 90%] Built target neper_m
[ 97%] Built target neper_v
[100%] Built target neper_s
[100%] Built target neper
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/neper
-- Set runtime path of "/usr/local/bin/neper" to ""
-- Installing: /usr/share/bash-completion/completions/neper
-- Installing: /usr/local/lib/pkgconfig/nlopt.pc
-- Installing: /usr/local/include/nlopt.h
-- Installing: /usr/local/include/nlopt.hpp
-- Installing: /usr/local/include/nlopt.f
-- Installing: /usr/local/share/man/man3/nlopt.3
-- Installing: /usr/local/share/man/man3/nlopt_minimize.3
-- Installing: /usr/local/share/man/man3/nlopt_minimize_constrained.3

**Comment by rquey** [comment]
Did you [install Gmsh](https://neper.info/doc/introduction.html#installing-neper)?

**Comment by fzw9381** [comment]
> Did you [install Gmsh](https://neper.info/doc/introduction.html#installing-neper)?

yes, I use:

sudo apt install libgmsh-dev

and successfully installed the Gmsh.

**Comment by fzw9381** [comment]
I tried version 4.3.1, some error happens.

and I tried 4.2.0, there is no such error.

**Comment by fzw9381** [comment]
I tried again, and there is still the same error. 
I believe this is a bug since version 4.3.0

**Comment by rquey** [comment]
I'm quite sure there is a problem with your Gmsh, but please run this:

```
gmsh --version
neper -T -n 2
neper -M n2-id1.tess -mesh3dclreps 1 -cl 0.5
```

and post the result: terminal output in the body of the message and output mesh file (if any) attached.

**Comment by fzw9381** [comment]
[files.zip](https://github.com/rquey/neper/files/8207038/files.zip)

all the message and files are in the attachment.

**Comment by fzw9381** [comment]
cpfem@cpfem:~/neper_test$ gmsh  --version
4.4.1

**Comment by fzw9381** [comment]
cpfem@cpfem:~/neper_test$ neper -T -n 2

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.4.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 4 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/cpfem/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 2
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :   - Setting seeds... 
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   : Writing results...
Info   :     [o] Writing file `n2-id1.tess'...
Info   :     [o] Wrote file `n2-id1.tess'.
Info   : Elapsed time: 0.022 secs.
========================================================================

**Comment by fzw9381** [comment]
cpfem@cpfem:~/neper_test$ neper -M n2-id1.tess

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.4.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 4 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2022, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/cpfem/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n2-id1.tess
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n2-id1.tess'...
Info   :     [i] Parsed file `n2-id1.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.3969) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing... 100% (0.44|0.8/100%| 0%| 0%) 
Info   :   - Fixing 2D-mesh pinches...
Info   :   - 3D meshing... 100% (0.89|0.89/100%| 0%| 0%)
Info   : Searching nsets and fasets...
Info   : Writing mesh results...
Info   :   - Preparing mesh...
Info   :   - Mesh properties:
Info   :     > Node number:       90
Info   :     > Elt  number:      232
Info   :     > Mesh volume:    1.000
Info   :   - Writing mesh...
Info   :     [o] Writing file `n2-id1.msh'...
Info   :     [o] Wrote file `n2-id1.msh'.
Info   : Elapsed time: 2.916 secs.
========================================================================

**Comment by rquey** [comment]
@fzw9381: Please do not post multiple messages - people receive a notification each time, and we aim at keeping this forum low trafiic - high quality. Edit your message instead.

I'll post a fix shortly.

**Comment by rquey** [comment]
It is only that you are testing Neper with a Gmsh version lower than the one used to build the reference test files, and your Gmsh version generates slightly different output files. You can read about this [here](https://neper.info/doc/introduction.html#testing-neper).

Either use the latest Gmsh version, 4.9.4, and re-run the tests, or keep your current configuration and re-run the tests in `Minimal` mode:

```
cmake -DBUILD_TESTING_MODE=Minimal ..
ctest
```

**Comment by RoadToDream** [comment]
For those who is confused with why neper can't pass the M series test, it may be due to the msh file generated from gmsh will have a  $MeshVersion section at the end. Which confuses function neut_mesh_fscanf_msh. 
```
$MeshVersion
2.2.3
$EndMeshVersion
```
