### ISSUE TITLE
Slice on periodic tesselations

### ISSUE THREAD

**Issue by DorianDepriester** [rquey/neper#44]
Hi Romain and thanks for this software.
I try to slice a periodic tessellation, but the transform step fails, leading to the infamous "core dumped" error. E.g. try:

    neper -T -n 10 -periodicity x -transform "slice(1,1,0,0)"

**Comment by rquey** [comment]
`-transform slice` is not available for periodic tessellations, and it does not seem trivial to add. What would you need it for?

**Comment by DorianDepriester** [comment]
Thanks for your quick answer.
I need to generate a bunch a slices in order to investigate the distribution of apparent grain size. In order to avoid the statistical bias introduced by the grains cropped by the ROI, I though it would be easier to use periodic conditions.

**Comment by DorianDepriester** [comment]
Ok, I got through it with ``-transform "rmcell(true==0)"``.

**Comment by rquey** [comment]
Here is a solution with periodic tessellations:
```
$ neper -T -n 10 -periodicity 1
$ neper -M n10-id1.tess -meshqualmin 0 -mesh3dclreps 1 -transform "slice(1,1,0,0)" -statelset diameq
```
It is quite dirty since you have to go through meshing (`-meshqualmin 0 -mesh3dclreps 1` speeds it up), but it serves your purpose.
Use version >= 3.5.2-27.
