### ISSUE TITLE
Quad dominant or all Quad mesh in 2D (preserving grain boundaries)

### ISSUE THREAD

**Issue by MiguelVCarvalho** [rquey/neper#45]
Include the possibility of having **Quad dominant** meshes or **All Quads** meshes in 2D.

For example with the options:
`-elttype quad_dominant`
`-elttype all_quad`

**Why:** If studying intergranular fracture with cohesive elements, the grain geometry is of utmost importance. Currently, only triangular elements preserve the grain geometry, since with the option `-elttype quad`, a regular grid is created.
However, if the grains are modelled with an incompressible material (as it is the case of crystal plasticity), the standard tri 3 and tri 6 elements should not be used since they are highly prone to volumetric locking.
In this case, quad 4 (FBAR for example) or quad 8 elements should be used.

**Case 1:**
Gmsh enables the user to choose "Recombine all triangular meshes" while meshing a geometry. This will lead to a quad dominant mesh.
Example:
![image](https://user-images.githubusercontent.com/25244490/74353802-57285580-4db2-11ea-82f5-f289405ae513.png)
![image](https://user-images.githubusercontent.com/25244490/74353826-61e2ea80-4db2-11ea-8dd6-3b57bfcc0a30.png)

(in this case, it was able to generate only quad elements but sometimes, due to complex geometry, some triangular elements remain)

**Case 2:**
Gmsh enables the user to change the Subdivision algorithm to "All Quads" while meshing a geometry. This will lead to a mesh that only contains quad elements (the element size may reduce).
Example:
![image](https://user-images.githubusercontent.com/25244490/74354049-b38b7500-4db2-11ea-82ce-a5f3671df625.png)
![image](https://user-images.githubusercontent.com/25244490/74354067-b9815600-4db2-11ea-8730-c8106f8fe570.png)

**Disclaimer:** These examples may not present the best meshes in terms of element quality but it was something done quite fast and only for demonstration purposes.

**Comment by MiguelVCarvalho** [comment]
To use the subdivision algorithm **All Quads**, the checkbox **Recombine all triangular meshes** has to be activated also. Otherwise, it will only break all triangles into 4 quads.

**Comment by rquey** [comment]
How would it translate in terms of entries in the .geo file? For tri/tet meshing, Neper uses this:
```
/* Options for the meshing: */
[...]
Mesh.Algorithm      = 6;
Mesh.Algorithm3D    = 4;
[...]
Mesh.SaveAll = 1;
Mesh.Optimize       = 1;
```

**Comment by MiguelVCarvalho** [comment]
Quad Dominant:

`Mesh.RecombinationAlgorithm = 3;` (blossom full-quad)
`Mesh.RecombineAll                  = 1;`

All Quads:
`Mesh.RecombinationAlgorithm = 3;` (blossom full-quad)
`Mesh.RecombineAll                  = 1;`
`Mesh.SubdivisionAlgorithm       = 1;` (All quads)

Something like this might work.

**Comment by rquey** [comment]
@MiguelVCarvalho - As of version 3.5.3-29, a mesh can be written under format msh version 4, using `-format msh4`. The mesh file can then be processed externally (by Gmsh) to get a full-quad mesh.

Here is an example:
$ neper -T -n 2 -dim 2
$ neper -M n2-id1.tess -format msh
$ gmsh -2 n2-quad.geo

This is only a start - it will be integrated to Neper more thoroughly.

n2-quad.geo:
```
Merge "n2-id1.msh4";
Mesh.RecombinationAlgorithm = 1;
RecombineMesh;
Mesh.SecondOrderLinear = 1;
Mesh.SubdivisionAlgorithm = 1;
RefineMesh;
```
