### ISSUE TITLE
Generating periodic boundary conditions for Tetrahedral elements in a unit cell

### ISSUE THREAD

**Issue by pawanchaugule** [rquey/neper#49]
Hello,

I am generating a tessellation of 50 elements unit cell using the following command: 
```
neper -T -n 50 -domain "cube(1,1,1)" -oricrysym cubic -ori uniform -o 50grains -oridescriptor e -regularization 1 -oriformat geof
```
I then mesh the tessellation using the command: 
```
neper -M 50grains.tess -elttype tet -order 1 -meshqualmin 1.0 -rcl 1 -o 50grains_tet -format geof
```
which gives me a mesh with tetrahedral elements as shown in the attachment. I am now trying to generate Periodic Boundary conditions on this unit cell by using periodic vectors. I tried using the vectors (1,0,0), (0,1,0) & (0,0,1) but was not able to make the unit cell periodic. If anyone tried anything similar, can you kindly share your suggestions ?

![Capture2](https://user-images.githubusercontent.com/61324520/75050864-739f4e80-5492-11ea-9693-2e0e77c15612.PNG)

Thank you

**Comment by rquey** [comment]
If you want a periodic mesh, you need a periodic tessellation:
```
neper -T -n 50 -domain "cube(1,1,1)" -oricrysym cubic -ori uniform -o 50grains -oridescriptor e -regularization 0 -oriformat geof -per 1
neper -M 50grains.tess -elttype tet -order 1 -meshqualmin 1.0 -rcl 1 -pl 1000 -o 50grains_tet -format geof
```
Note that regularization was disabled (not available for periodic tessellations) and `-pl 1000` was added.

**Comment by Hejie-Guo** [comment]
Hi, 
I am trying to generate a periodic unit cell with the command you answer in #49.
But when I use the command "neper -M 50grains.tess -elttype tet -order 1 -meshqualmin 1.0 -rcl 1 -pl 1000 -o 50grains_tet -format geof" I get the false message as following:

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.1.2
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 2 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/guohejie/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] 50grains.tess -elttype tet -order 1 -meshqualmin 1.0
         -rcl 1 -pl 1000 -o 50grains_tet -format geof
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `50grains.tess'...
Info   :     [i] Parsed file `50grains.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.1357) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing... 100% (0|0.49/94%| 5%| 1%)
Info   :   - Fixing 2D-mesh pinches...
Info   :   - 3D meshing... Error  :     > Meshing of poly 1 (1) failed
Aborted (core dumped)
