### ISSUE TITLE
-M -rcl 'file(file_name)'

### ISSUE THREAD

**Issue by bibiboom89** [rquey/neper#54]
Hi Romain Quey,

I have a quick question about the "-rcl" command. In the documentation file from the 12th March 2020, it is written page 30 that the rcl value can be loaded "from an external file using the syntax ‘file(file_name)". But I didn't find any description of the file format.
Is it just a list of values such as:     
poly_id rcl_value
 or 
seed_id rcl_value

Also, if all the seeds (or polyhedron) do not appear in this file, what value do they get?

I thank you in advance,
Regards,
Dr. R. Bretin

**Comment by rquey** [comment]
The file must contain only the rcl data, in expected number.  I've clarified this in the documentation.
