### ISSUE TITLE
Using statistics to determine the morphology of 2D structures

### ISSUE THREAD

**Issue by CrownUpKid** [rquey/neper#55]
Hello,
im trying to use some statistics, i extraced from EBSD Analysis, to create 2D synthetic structures. For better understanding i tried to use some examples from the documentation. In the description it says that -morpho 'gg' is equal to the term - morpho ‘diameq:lognormal(1,0.35),1-sphericity:lognormal(0.145,0.03)’. According to my understanding, the same seed should produce the same results, which is not the case. Do I have a wrong understanding, or is it a bug? For reference, this is the full command im using:
neper -T -dim 2 -domain "square(1,1)" -n 100 -o "Micro_2D"
-morpho 'gg' -id 10

and 

neper -T -dim 2 -domain "square(1,1)" -n 100 -o "Micro_2D"
-morpho ‘diameq:lognormal(1,0.35),1-sphericity:lognormal(0.145,0.03)’ -id 10

glad if i get some help

**Comment by rquey** [comment]
`gg` actually has different values in 2D and 3D (which was not indicated in the doc). The value you used is for 3D. In 2D, it is `"diameq:lognormal(1,0.42),1-sphericity:lognormal(0.100,0.03)"`.
