### ISSUE TITLE
Support for MFEM mesh files as an output

### ISSUE THREAD

**Issue by rcarson3** [rquey/neper#59]
Hi @rquey ,

As part of an exascale computing project, I've put together and released a next-gen crystal plasticity FEM code called [ExaConstit](https://github.com/LLNL/ExaConstit), which is based on the MFEM library.  If you haven't heard of MFEM it's a really nice FEM library that can run some [pretty cool problems](https://mfem.org/gallery/). While ExaConstit is still young and under rather active development, it's able to run some[ medium sized simulations (~200k quad tets)](https://github.com/LLNL/ExaConstit/pull/3#issuecomment-603418895) out to large strains on just a desktop computer in a couple of hours when making use of just the CPU cores. If you've got access to a cluster or GPU cluster you can run some rather large problems no issue.

Currently in order to make use of cube-like meshes generated from Neper, I need to output meshes as an FEpX type, convert those over to an old version of VTK, slurp those up into a MFEM based executable to get out a usable mesh file with all of the grain ids and surface boundary IDs labelled. If my users wanted to potentially run a sample that looks like the tensile test tessellation on the neper web-page this workflow kinda falls apart. Therefore, I was wondering if it might be possible to have neper directly output the mesh file into the [MFEM mesh v1.0 file format](https://mfem.org/mesh-formats/#mfem-mesh-v10). Element attributes here are the grain ids and boundary attributes are the surface id/#, and we would only need linear elements printed out since MFEM is capable of increasing the order of the mesh internally.

Cheers,
Robert

**Comment by rcarson3** [comment]
@rquey I'm closing this now, since I've found the gmsh v2 format mainly works for my needs.

Although, I still need to edit that file to only list the external 2d surface elements and assign them an attribute that corresponds to what external surface they lie on rather than a value that corresponds to a grain surface. I'm using the `faset` option to generate the necessary list of surface elements, and it sounds like from the documentation that this should work for more complicated geometries as well.

**Comment by rquey** [comment]
Sorry this one got buried out... Please leave the issue open if you still want the format to be supported. It may happen at some point...

**Comment by rcarson3** [comment]
It's okay. I'm going to have one of my users, who has quite a few Neper meshes already, test out a python tool I'm writing to see if this gmsh way isn't too difficult for them. So, I might in a few weeks re-open it per your suggestion after I get their feedback.
