### ISSUE TITLE
multi-scale tessellation

### ISSUE THREAD

**Issue by xajezade** [rquey/neper#62]
Hi there,

when I use the following command to generate microstructure, it fails at some point in the middle of the generation.
>>neper -T -n from_morpho::from_morpho -dim 2 -domain "square(2048,2048)" -morpho "square(16)::diameq:lognormal(1.57,0.55)"  -morphooptistop "val=0.001::val=0.001" -o 2DBigRandom  -format tess,ori -statface nfaces_samedomain

if I use "square(8)" in place of "square(16)", I could get it done. I don't know if it is by chance or not. If I use "-morphooptialgo praxis", I can do "square(16)". 

In all cases, if I use vtk or tesr as my output format, it gives me an error. I need to use the produced tess file, to load it again using "-loadtess" to generate vtk files. 

I am using neper Version 3.5.2-34.

Kindest Regards,
Ali

**Comment by rquey** [comment]
This is old and too far from a MWE for troubleshooting. Closing.
