### ISSUE TITLE
Questions about sphere size

### ISSUE THREAD

**Issue by momohu** [rquey/neper#64]
Why do I choose a diameter of 1m, but the resulting size is 5m
neper -T -n 100 -domain "sphere(1)"  -o sphere -format geo
![2020-05-27 20-56-25 的屏幕截图](https://user-images.githubusercontent.com/59075419/83021493-aa21d200-a05c-11ea-8b90-ed14db0eafed.png)

**Comment by jcappola** [comment]
This seems to be a bug in the domain parameter parsing for the tessellation module. In the file `neper/src/neper_t/net_domain/net_domain2.c` on line 209 we see:

`` parms[0] += 4;``

which adds 4 to the user input diameter value. Simply remove this line and recompile to fix the issue.

@rquey: I'm not sure if this is here on purpose, but I think may have been a typo regarding `parms[1]` for the number of facets which needs to be at minimum a value of 4.
