### ISSUE TITLE
Neper installation error

### ISSUE THREAD

**Issue by babakrav** [rquey/neper#66]
Hi 
I am trying to install Neper for my user on our uinversity's cluster. As instructed in the documentaion, I receive the following message after `cmake ..` 

```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- WARNING: you are using the obsolete 'PKGCONFIG' macro, use FindPkgConfig
-- PKGCONFIG() indicates that gsl is not installed (install the package which contains gsl.pc if you want to support this feature)
FindGSL.cmake: gsl-config/pkg-config gsl not found. Please set
it manually. GSL_CONFIG=GSL_CONFIG-NOTFOUND
CMake Error at CMakeLists.txt:22 (_message):
  GSL required, please specify it's location.
Call Stack (most recent call first):
  cmake/FindGSL.cmake:178 (MESSAGE)
  CMakeLists.txt:115 (find_package)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NLOPT_INCLUDE_DIR
   used as include directory in directory /home/bravaji/Neper/neper-3.5.2/src/contrib/orilib
   used as include directory in directory /home/bravaji/Neper/neper-3.5.2/src/neut
   used as include directory in directory /home/bravaji/Neper/neper-3.5.2/src/neper_t
   used as include directory in directory /home/bravaji/Neper/neper-3.5.2/src/neper_m
   used as include directory in directory /home/bravaji/Neper/neper-3.5.2/src/neper_v
NLOPT_LIBRARY
    linked by target "orilib" in directory /home/bravaji/Neper/neper-3.5.2/src/contrib/orilib
    linked by target "neut" in directory /home/bravaji/Neper/neper-3.5.2/src/neut
    linked by target "neper_t" in directory /home/bravaji/Neper/neper-3.5.2/src/neper_t
    linked by target "neper_m" in directory /home/bravaji/Neper/neper-3.5.2/src/neper_m
    linked by target "neper_v" in directory /home/bravaji/Neper/neper-3.5.2/src/neper_v

-- Configuring incomplete, errors occurred!
See also "/home/bravaji/Neper/neper-3.5.2/src/build/CMakeFiles/CMakeOutput.log".
```

What should I do about the ERROR messages? Please note that I do not have admin privilege and I am not allowed to install packages using `sudo `

**Comment by jcappola** [comment]
Hi @babakrav, these errors are just to let you know that the CMake build was unable to find NLOPT on your cluster's system automatically. **Also, it looks like GSL was not found automatically.** Note that NLOPT is not a mandatory package while GSL is. 

I recommend running `ccmake ..` (note the extra `c`) which will allow for an interactive build configuration process. From there, you can try setting `HAVE_NLOPT` to `OFF` and adjust the entries for `GSL_CONFIG`, `GSL_CONFIG_PREFER_PATH`, and `GSL_EXE_LINKER_FLAGS`, according to your cluster's system. You may need to contact your system administrators to see how to load GSL (from a module or otherwise) in order to install. The previous console logs you've previously posted noted that Neper was, indeed, built with GSL so it should be available on your system.

**Comment by tomidall** [comment]
Hi 

I am trying to install neper on ubuntu based on the PDF file which is provided for the software. After installation, I ran "make test" to check, but it seems the following parts were not installed. Could you please help me with this?

Best

Milad

52% tests passed, 138 tests failed out of 286

Total Test time (real) =  83.98 sec

The following tests FAILED:
         86 - Tm2_morpho_centroidal (Child aborted)
         91 - Tm2_morpho_cube (Child aborted)
        104 - Tm3_morpho_cube (Child aborted)
        116 - M_meshing (Child aborted)
        118 - M_cl (Child aborted)
        119 - M_rcl (Child aborted)
        124 - M_cl_expr (Child aborted)
        125 - M_rcl_expr (Child aborted)
        126 - M_dim (Child aborted)
        127 - M_dim2 (Child aborted)
        128 - M_dim_expr (Child aborted)
        129 - M_order (Child aborted)
        133 - M_pl (Child aborted)
        134 - M_clratio (Child aborted)
        135 - M_clmin (Child aborted)
        137 - M_meshqualexpr (Child aborted)
        138 - M_meshqualdisexpr (Child aborted)
        139 - M_mesh2dalgo_mead (Child aborted)
        140 - M_mesh2dalgo_dela (Child aborted)
        141 - M_mesh2dalgo_fron (Child aborted)
        142 - M_mesh2dalgo_netg (Child aborted)
        143 - M_mesh3dalgo_netgnetg (Child aborted)
        144 - M_mesh3dalgo_netggmsh (Child aborted)
        145 - M_mesh3dalgo_netggmne (Child aborted)
        153 - M_remesh1 (Child aborted)
        154 - M_remesh2 (Child aborted)
        155 - M_remesh3 (Child aborted)
        156 - M_nset1 (Child aborted)
        157 - M_nset2 (Child aborted)
        158 - M_nset3 (Child aborted)
        159 - M_faset (Child aborted)
        173 - M_interface (Child aborted)
        174 - M_interface2 (Child aborted)
        179 - V_pretest3 (Child aborted)
        181 - V_pretest5 (Child aborted)
        183 - V_seedcol_per (Child aborted)
        184 - V_seedcol_rgb (Child aborted)
        185 - V_seedcol_rgb2 (Child aborted)
        186 - V_seedcol_id (Child aborted)
        187 - V_seedcol_real (Child aborted)
        188 - V_seedcol_scal_colscheme (Child aborted)
        189 - V_seedscale (Child aborted)
        190 - V_seedscale2 (Child aborted)
        191 - V_seedscaletitle (Child aborted)
        192 - V_seedtrs (Child aborted)
        193 - V_vercol_rgb (Child aborted)
        194 - V_vercol_rgb2 (Child aborted)
        195 - V_vercol_id (Child aborted)
        196 - V_vercol_real (Child aborted)
        197 - V_vercol_scal_colscheme (Child aborted)
        198 - V_verscale (Child aborted)
        199 - V_verscale2 (Child aborted)
        200 - V_verscaletitle (Child aborted)
        201 - V_vertrs (Child aborted)
        202 - V_edgecol_rgb (Child aborted)
        203 - V_edgecol_rgb2 (Child aborted)
        204 - V_edgecol_id (Child aborted)
        205 - V_edgecol_real (Child aborted)
        206 - V_edgecol_scal_colscheme (Child aborted)
        207 - V_edgescale (Child aborted)
        208 - V_edgescale2 (Child aborted)
        209 - V_edgescaletitle (Child aborted)
        210 - V_edgetrs (Child aborted)
        211 - V_facecol_rgb (Child aborted)
        212 - V_facecol_rgb2 (Child aborted)
        213 - V_facecol_id (Child aborted)
        214 - V_facecol_real (Child aborted)
        215 - V_facecol_scal_colscheme (Child aborted)
        216 - V_facescale (Child aborted)
        217 - V_facescale2 (Child aborted)
        218 - V_facescaletitle (Child aborted)
        219 - V_facetrs (Child aborted)
        220 - V_polycol_rgb (Child aborted)
        221 - V_polycol_rgb2 (Child aborted)
        222 - V_polycol_id (Child aborted)
        223 - V_polycol_real (Child aborted)
        224 - V_polycol_scal_colscheme (Child aborted)
        225 - V_polyscale (Child aborted)
        226 - V_polyscale2 (Child aborted)
        227 - V_polyscaletitle (Child aborted)
        228 - V_polytrs (Child aborted)
        229 - V_cellcol_rgb (Child aborted)
        230 - V_cellcol_rgb2 (Child aborted)
        231 - V_cellcol_id (Child aborted)
        232 - V_cellcol_real (Child aborted)
        233 - V_cellcol_scal_colscheme (Child aborted)
        234 - V_cellscale (Child aborted)
        235 - V_cellscale2 (Child aborted)
        236 - V_cellscaletitle (Child aborted)
        237 - V_celltrs (Child aborted)
        238 - V_cellcol_ori (Child aborted)
        239 - V_verrad (Child aborted)
        240 - V_csys (Child aborted)
        241 - V_csyscoo (Child aborted)
        242 - V_csyslength (Child aborted)
        243 - V_csysrad (Child aborted)
        244 - V_csyslabel (Child aborted)
        245 - V_csyscol (Child aborted)
        246 - V_nodecol (Child aborted)
        247 - V_nodecol_real (Child aborted)
        248 - V_nodecolscheme (Child aborted)
        249 - V_nodescale (Child aborted)
        250 - V_nodescale2 (Child aborted)
        251 - V_elsetcol (Child aborted)
        252 - V_elsetcol_real (Child aborted)
        253 - V_elsetcolscheme (Child aborted)
        254 - V_elsetscale (Child aborted)
        255 - V_elsetscale2 (Child aborted)
        256 - V_elsetscaletitle (Child aborted)
        257 - V_elsetcol_ori (Child aborted)
        258 - V_nodecoo (Child aborted)
        259 - V_nodecoo_disp (Child aborted)
        260 - V_nodecoofact (Child aborted)
        261 - V_slicemesh (Child aborted)
        262 - V_slicemesh2 (Child aborted)
        263 - V_showmesh1 (Child aborted)
        264 - V_showmesh2 (Child aborted)
        265 - V_slicemesh3 (Child aborted)
        266 - V_slicemesh4 (Child aborted)
        267 - V_slicemesh5 (Child aborted)
        268 - V_slicemesh6 (Child aborted)
        269 - V_show (Child aborted)
        270 - V_showfaceinter (Child aborted)
        271 - V_showelt (Child aborted)
        272 - V_dataelt3d (Child aborted)
        273 - V_cameracoo1 (Child aborted)
        274 - V_cameracoo2 (Child aborted)
        275 - V_cameracoo3 (Child aborted)
        276 - V_cameralookat1 (Child aborted)
        277 - V_cameralookat2 (Child aborted)
        278 - V_cameralookat3 (Child aborted)
        279 - V_cameraangle (Child aborted)
        280 - V_camerasky (Child aborted)
        281 - V_cameraprojection (Child aborted)
        282 - V_imagesize (Child aborted)
        283 - V_imagebackground (Child aborted)
        284 - V_imageantialias (Child aborted)
        286 - V_loop (Child aborted)
Errors while running CTest
make: *** [Makefile:107: test] Error 8

**Comment by rquey** [comment]
You have to install Gmsh and Povray.

**Comment by tomidall** [comment]
> You have to install Gmsh and Povray.

Thank you for your quick response.

Best

**Comment by tomidall** [comment]
Dear Dr. Quey,

I have installed both Gmsh and Povray. Gmsh is available at the terminal, but Povray shows the following error. Could you please help me?

Regards,

Milad

povray: /home/milad/.povray/3.7/povray.conf: 7: the user setting 'allowed' for [Shellout Security] is less restrictive than the system 'forbidden' setting in '/etc/povray/3.7/povray.conf': using system setting

Problem with option setting
povray
No input file provided

**Comment by rquey** [comment]
@tomidall, I can't really help, but it looks like warnings rather than errors... Do the `-V` tests pass now?

If `Tm2_morpho_centroidal`, `Tm2_morpho_cube` and `Tm3_morpho_cube`? still fail, please run the commands they correspond to and paste here Neper's terminal output:
- Tm2_morpho_centroidal: `./neper --rcfile none -T -n 2::2 -morpho centroidal::centroidal`
- Tm2_morpho_cube: `./neper --rcfile none -T -n from_morpho::5 -morpho "cube(2)::voronoi"`
- Tm3_morpho_cube: `./neper --rcfile none -T -n from_morpho::2::2 -morpho "cube(2)::voronoi::voronoi"`

**Comment by tomidall** [comment]
Hi Dr. Quey,

Unfortunately, still -v tests are not passed. Here is the Neper's terminal output for the commands mentioned above, respectively.

Best
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.0.1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 2::2 -morpho centroidal::centroidal
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellations...
Info   :   [level] Running in multiscale mode (2 scales)...
Info   :   [    1]  1/1 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.269544489
Info   :     > Iteration     76: fmin=0.000093337 f=0.000093337
Info   :     > Reached unknown criterion.
Info   :   [    2]  1/2 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.562528677
Info   :     > Iteration     82: fmin=0.000099938 f=0.000099938
Info   :     > Reached unknown criterion.
Info   :   [    2]  2/2 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.390659819
Info   :     > Iteration     77: fmin=0.000097528 f=0.000097528
Info   :     > Reached unknown criterion.
Info   : Flattening 2-scale tessellation...
Info   :   [level] Flattening 2-scale tessellation...
Info   :   [    1]  1/1: id=1
Info   : Writing results...
Info   :     [o] Writing file `n2::2-id1::1.tess'...
Info   :     [o] Wrote file `n2::2-id1::1.tess'.
Info   : Elapsed time: 0.157 secs.
========================================================================


========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.0.1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n from_morpho::5 -morpho cube(2)::voronoi
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellations...
Info   :   [level] Running in multiscale mode (2 scales)...
Info   :   [    1]  1/1 Info   :   - Running tessellation...
Info   :   - Generating crystal orientations...
Info   :   [    2]  1/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  2/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  3/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  4/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  5/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  6/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  7/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  8/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   : Flattening 2-scale tessellation...
Info   :   [level] Flattening 2-scale tessellation...
Info   :   [    1]  1/1: id=1
Info   : Writing results...
Info   :     [o] Writing file `nfrom_morpho::5-id1::1.tess'...
Info   :     [o] Wrote file `nfrom_morpho::5-id1::1.tess'.
Info   : Elapsed time: 0.081 secs.
========================================================================


========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.0.1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : Ignoring initialization file.
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n from_morpho::2::2 -morpho
         cube(2)::voronoi::voronoi
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellations...
Info   :   [level] Running in multiscale mode (3 scales)...
Info   :   [    1]  1/1 Info   :   - Running tessellation...
Info   :   - Generating crystal orientations...
Info   :   [    2]  1/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  2/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  3/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  4/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  5/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  6/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  7/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    2]  8/8 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  1/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  2/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  3/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  4/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  5/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  6/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  7/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  8/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  9/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  10/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  11/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  12/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  13/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  14/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  15/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :   [    3]  16/16 Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   : Flattening 3-scale tessellation...
Info   :   [level] Flattening 3-scale tessellation...
Info   :   [    2]  8/8: id=9
Info   :   [    1]  1/1: id=1
Info   : Writing results...
Info   :     [o] Writing file `nfrom_morpho::2::2-id1::1::1.tess'...
Info   :     [o] Wrote file `nfrom_morpho::2::2-id1::1::1.tess'.
Info   : Elapsed time: 0.165 secs.
========================================================================

**Comment by rquey** [comment]
Thanks.  Please update to version 4.0.2.

**Comment by tomidall** [comment]
Hi Dr. Quey,

I installed version 4.0.2 and the unpassed tests are decrease to the following.

Regards,

Milad

90% tests passed, 28 tests failed out of 282

Total Test time (real) = 261.27 sec

The following tests FAILED:
        118 - M_cl (Child aborted)
        119 - M_rcl (Child aborted)
        124 - M_cl_expr (Child aborted)
        126 - M_dim (Child aborted)
        127 - M_dim2 (Child aborted)
        129 - M_order (Child aborted)
        133 - M_pl (Child aborted)
        137 - M_meshqualexpr (Child aborted)
        139 - M_mesh2dalgo_mead (Child aborted)
        140 - M_mesh2dalgo_dela (Child aborted)
        141 - M_mesh2dalgo_fron (Child aborted)
        143 - M_mesh3dalgo_netgnetg (Child aborted)
        144 - M_mesh3dalgo_netggmsh (Child aborted)
        145 - M_mesh3dalgo_netggmne (Child aborted)
        152 - M_nset1 (Child aborted)
        154 - M_nset3 (Child aborted)
        155 - M_faset (Child aborted)
        169 - M_interface (Child aborted)
        170 - M_interface2 (Child aborted)
        175 - V_pretest3 (Child aborted)
        177 - V_pretest5 (Child aborted)
        254 - V_nodecoo (Child aborted)
        255 - V_nodecoo_disp (Child aborted)
        256 - V_nodecoofact (Child aborted)
        258 - V_slicemesh2 (Child aborted)
        270 - V_cameracoo2 (Child aborted)
        271 - V_cameracoo3 (Child aborted)
        282 - V_loop (Child aborted)
Errors while running CTest
