### ISSUE TITLE
Bug in Neper when trying to create a Laguerre-Voronoi tessellation from seed position and weight files

### ISSUE THREAD

**Issue by cegriesbach** [rquey/neper#67]
Hello,
I am trying to create a tessellation using seed position and weight data using the morphoortiini option. The "seed_positions.txt" and "weights.txt" files are tab delimited with 7996x3 and 7996x1 values, respectively. This is the command line I use and subsequent output (see below). I am new to Neper, so any help would be appreciated! 
Thanks,
Claire

neper -T -n 7996 -morphooptiini 'coo:file(seed_positions.txt),weight:file(weights.txt)'    
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 3.5.2
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 72 threads.
Info   : <http://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/cegriesbach/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 7996 -morphooptiini
         coo:file(seed_positions.txt),weight:file(weights.txt)
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

**Comment by rquey** [comment]
The command is correct. I can't help more without the input files...

**Comment by cegriesbach** [comment]
Here are the input files
[seed_positions.txt](https://github.com/rquey/neper/files/4859876/seed_positions.txt)
[weights.txt](https://github.com/rquey/neper/files/4859878/weights.txt)

**Comment by rquey** [comment]
You have to define the domain using `-domain`. It defaults to `cube(1,1,1)` which is probably not what you want given the input.

**Comment by cegriesbach** [comment]
I tried that, but it still fails and says there is a bug.

**Comment by cegriesbach** [comment]
I got one to work using different seed_positions and weights files. Maybe there was something wrong with that file. Thanks for your help!
