### ISSUE TITLE
Tessellation method from CAD data

### ISSUE THREAD

**Issue by kyohei-ga-kiku** [rquey/neper#68]
Can I create a tessellation files from 3D-CAD data  such as dxf , dwg, jww or anything.

**Comment by rquey** [comment]
No, it cannot, at least directly. See option `-domain` for current possibilities.

**Comment by kyohei-ga-kiku** [comment]
Thank you for your response.
In fact, I want to prepare the tessellation file of cylindrical shape with a U-notch... 
I have no idea for this.
And I hope additional function that enables to import domain definition from CAD data in next coming neper version!!!

**Comment by kyohei-ga-kiku** [comment]
Thank you for your response.
In fact, I want to prepare the tessellation file of cylindrical shape with a U-notch... 
I have no idea for this.
And I hope the function that enables to import tessellation shape from CAD data in next coming neper version!!!
