### ISSUE TITLE
multi-scale tessellation problem

### ISSUE THREAD

**Issue by wz116529385** [rquey/neper#70]
Dear Romain,
  when I use the following command to generate a two-scale of microstructure, it fails with Segmentation fault. I have no idea how to deal with it.
 Any advices will be appreciated!

`neper -T -n from_morpho::5  -morpho "msfile(n10.tess)::gg" -o test9`

Best Regards
Wang
[n10.zip](https://github.com/rquey/neper/files/5062771/n10.zip)

**Comment by wz116529385** [comment]
And here is the .tess file.

**Comment by wz116529385** [comment]
And here is the .tess file.

**Comment by wz116529385** [comment]
And here is the .tess file.

**Comment by wz116529385** [comment]
And here is the .tess file.

**Comment by wz116529385** [comment]
And here is the .tess file.

**Comment by xajezade** [comment]
Hi there,

I have the same problem with the new version of Neper. I have no problem running it on version 3.5.3-20.

Best,
Ali

**Comment by wz116529385** [comment]
Thank you xajezade,  I've tried. It's true, and It is expected to be fixed in version 4.00.

**Comment by wz116529385** [comment]
> 
> 
> Hi there,
> 
> I have the same problem with the new version of Neper. I have no problem running it on version 3.5.3-20.
> 
> Best,
> Ali

Thank you Ali, I've tried. It's true, and It is expected to be fixed in version 4.00.

**Comment by rquey** [comment]
Thanks for the bug report. This is now fixed.

Of note, you shoud use `-morpho "file(n10.tess)::gg"` instead of `-morpho "msfile(n10.tess)::gg"`, as `n10.tess` is a standard tessellation file (not a multiscale file).

**Comment by wz116529385** [comment]
> 
> 
> Thanks for the bug report. This is now fixed.
> 
> Of note, you shoud use `-morpho "file(n10.tess)::gg"` instead of `-morpho "msfile(n10.tess)::gg"`, as `n10.tess` is a standard tessellation file (not a multiscale file).

Many thanks for your help, Romain. I have solved the problem of the two scale modelling with the file n10.tess. However, another problem was come out，that is when i used the command`-morpho "file(n10.tess)::gg" with a large number of cells of file,like n11.tess, which was generated by a set of seed, it failed again. Can you help me straighten it out?
[n11.zip](https://github.com/rquey/neper/files/5089328/n11.zip)

![图片](https://user-images.githubusercontent.com/69336123/90492067-56161d80-e173-11ea-9e35-882e74dd1027.png)

**Comment by rquey** [comment]
Use version 4.0.1-4 or later, from the `main`branch, both to generate `n11.tess` and to run the command.

**Comment by wz116529385** [comment]
> 
> 
> Use version 4.0.1-4 or later, from the `main` branch, both to generate `n11.tess` and to run the command.

Thanks, i will try it later.

**Comment by wz116529385** [comment]
Hi，Romain. 
   The website 'neper.info' doesn't work these days, Is anything wrong? 
Best regards.
Wang

**Comment by wz116529385** [comment]
> 
> 
> Use version 4.0.1-4 or later, from the `main` branch, both to generate `n11.tess` and to run the command.
Hi Romain,
  I have no idea about how to generate the n11.tess (which is generated from a large number of seeds ) and scale 2 at the same time. Can you show me an example? thanks.
Best wishes
Wang.

**Comment by rquey** [comment]
You don't have to do it at the same time. Do you know the command you used to generate `n11.tess`?

**Comment by wz116529385** [comment]
Here is the commands used to generate scale2, but it fails.
[node2.txt](https://github.com/rquey/neper/files/5096405/node2.txt)
`gsl-randist 1 6417 flat 0 0.000001 > x`
`gsl-randist 2 6417 flat 0 0.000001 > y`
`gsl-randist 3 6417 flat 0 0.000001 > z`
`paste node2.txt x y z | awk '{print $1+$4,$2+$5,$3+$6}' > pos2`
`neper -T -n 6417 -domain 'cylinder(0.1,0.05,100)' -morphooptiini "coo:file(pos2)" -o n11`
`neper -T -n from_morpho::5  -morpho 'file(n11.tess)::centroidal' -o scale2`

**Comment by rquey** [comment]
You have to define the domain on your last command:
```
neper -T -domain 'cylinder(0.1,0.05,100)' -n from_morpho::5 -morpho 'file(n11.tess)::centroidal' -o scale2
```

**Comment by wz116529385** [comment]
> 
> 
> You have to define the domain on your last command:
> 
> ```
> neper -T -domain 'cylinder(0.1,0.05,100)' -n from_morpho::5 -morpho 'file(n11.tess)::centroidal' -o scale2
> ```

Yes， it works. Thank you.

**Comment by wz116529385** [comment]
Another problem, when i ran the command above, it stops at 3116 steps with a bug report error. 

> Info   :   [    2]  3113/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.180283066
Info   :     > Iteration     64: fmin=0.000090201 f=0.000090201
Info   :     > Reached unknown criterion.
Info   :   [    2]  3114/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.386203982
Info   :     > Iteration     75: fmin=0.000091994 f=0.000091994
Info   :     > Reached unknown criterion.
Info   :   [    2]  3115/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.254175327
Info   :     > Iteration     51: fmin=0.000094078 f=0.000094078
Info   :     > Reached unknown criterion.
Info   :   [    2]  3116/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =3350.021954288
Info   :     > Iteration      1: fmin=3350.021954288 f=3350.021954288(*pTOpt).curval[0] is not-a-number.
Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

**Comment by wz116529385** [comment]
Hi Romain
  Another problem arose, When I ran the command above to  generate the scale2, it stopped at 3116 steps with a bug report error:

> Info   :   [    2]  3115/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =0.254175327
Info   :     > Iteration     51: fmin=0.000094078 f=0.000094078
Info   :     > Reached unknown criterion.
Info   :   [    2]  3116/6417 Info   :   - Setting seeds... 100%
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   :     > Initial solution: f   =3350.021954288
Info   :     > Iteration      1: fmin=3350.021954288 f=3350.021954288(*pTOpt).curval[0] is not-a-number.
Error  : You have discovered a bug in Neper!  Please file an issue at
         https://github.com/rquey/neper/issues.  Thank you.

Meanwhile, I have noticed that if i change the domain to "cube(0.06,0.06,0.11)" which contained all the seeds, it was fine. So I think the cause of the error is maybe the empty cells.
Best Regards
Wang.

**Comment by rquey** [comment]
Yes, most issues come from empty of very small cells.

You should probably identify the seeds that generate empty or very small cells using
```
 neper -T -n 6417 -domain 'cylinder(0.1,0.05,100)' -morphooptiini "coo:file(pos2)" -o n11 -statcell vol
```
remove those seeds from `pos2`, and re-run the tessellation.

**Comment by wz116529385** [comment]
> neper -T -n 6417 -domain 'cylinder(0.1,0.05,100)' -morphooptiini "coo:file(pos2)" -o n11 -statcell vol

OK thanks.
