### ISSUE TITLE
multi-scale tessellation is failed at flattening stage

### ISSUE THREAD

**Issue by xajezade** [rquey/neper#71]
Hi there,

the following commands are failed at the final stage:
`neper -T -dim 2 -n from_morpho -morpho "diameq:0.66*lognormal(6.94,5.85,from=1)+0.34*lognormal(6.94,5.85,from=1),1-sphericity:lognormal(0.05,0.01)" -domain "square(409.6,128)" -tesrsize 4096:1280 -statcell mode -o scale1 -format tess,tesr,vtk`
`awk '{if ($1==1) {print NR,"diameq:lognormal(2.4,0.67),1-sphericity:lognormal(0.145,0.03)"} else {print NR,"diameq:lognormal(2.88,0.67),1-sphericity:lognormal(0.145,0.03)"}}' scale1.stcell > scale2-morpho`
`neper -T -n 343 -domain "cube(409.6,128,256)" -morphooptiini "coo:file(scale1.tess),weight:file(scale1.tess)" -morpho "columnar(z)" -o scale1-3D -format tess`
`neper -T -dim 3 -domain "cube(409.6,128,256)" -n from_morpho::from_morpho -morpho "file(scale1-3D.tess)::file(scale2-morpho)" -morphooptistop "::val=0.01,eps=1e-4" -tesrsize "4096,1280,2560" -o final -for vtk,tess -statface nfaces_samedomain`

the final message:

> Iteration  47772: fmin=0.009994556 f=0.009994556
> Iteration  47773: fmin=0.009994556 f=0.009994556
> Info   :     > Reached `val' criterion.
>Info   : Flattening 2-scale tessellation...
>Info   :   [level] Flattening 2-scale tessellation...
>Info   :   [    1]  1/1: id=1                                           
>Error  : You have discovered a bug in Neper!  Please file an issue at
>         https://github.com/rquey/neper/issues.  Thank you.

It is worth mentioning that I had plenty of memory available and the system shows that only 20% of memory was utilized. It does complete without a problem if I use `-morphooptistop "::itermax=1"`.

Please let me know.

Kindest Regards,
Ali

**Comment by xajezade** [comment]
it works fine for a smaller domain size of 64*64*64.

**Comment by rquey** [comment]
This is old and too far from a MWE for troubleshooting. Closing.
