### ISSUE TITLE
Enable tessellation transform option from 2D to 3D

### ISSUE THREAD

**Issue by CarlHIT** [rquey/neper#73]
Hi, i wonder if Neper can add the transform option '3d' that can be use to transform a 2D tessellation with specify length along z direction into a 3D tessellation. Thank you for your unconditional support.

**Comment by rquey** [comment]
If what you want is to get a 3D mesh (1-element thick) of a 2D tessellation, it is already like this:
```
neper -T -n 10 -dim 2
neper -M n10-id1.tess -dim 3
neper -V n10-id1.msh -dataelsetcol id -print img
```
![image](https://user-images.githubusercontent.com/2659376/92076555-0c584480-edbb-11ea-9b23-4400a80bf32b.png)

**Comment by CarlHIT** [comment]
thx you for your reply, but it only works for tetahedra. if we make it  as hexahedral element, like this
```
neper -T -n 10 -dim 2
neper -M n10-id1.tess -elttype hex -dim 3
```
we cannot get a ouput file
thx

**Comment by rquey** [comment]
In that case, you can create a 3D tessellation from the 2D tessellation, and then mesh:
```
neper -T -n 10 -dim 2
neper -T -n 10 -domain "cube(1,1,0.1)" -morphooptiini "coo:file(n10-id1.tess),weight:file(n10-id1.tess)" -o n10-id1-3d
neper -M n10-id1-3d.tess -elttype hex
neper -V n10-id1-3d.msh -dataelsetcol id -print img
```

![image](https://user-images.githubusercontent.com/2659376/92089611-afff2000-edce-11ea-955f-3d824ffa26dc.png)

**Comment by CarlHIT** [comment]
Thank you very much
