### ISSUE TITLE
Generating Non-Equiaxed Grains

### ISSUE THREAD

**Issue by darrencpagan** [rquey/neper#77]
I was wondering what the simplest way of generating non-equiaxed grains is? In particular, I'd like to generate 'pancake' grains with two long dimensions and one short dimension (say 5 x 5 x 1 dimension ratio). Is this possible with the tesselation module?

**Comment by rquey** [comment]
Hi @darrencpagan. It's `-morpho "aspratio(5,5,1)"`.

**Comment by darrencpagan** [comment]
@rquey Thank you for the help!
