### ISSUE TITLE
Generating a mesh with tetrahedral elements for a cylinder - Meshing failed

### ISSUE THREAD

**Issue by aaditya8959** [rquey/neper#78]
Hi,  

   I was trying to mesh a tessellation of a cylindrical sample microstructure, with the tessellation also generated using Neper(Version 4.1.0), as follows :

1) Generate Tessellation

```
neper -T -n 50 -domain 'cylinder(4,2)'  -reg 1
```

which ran successfully to produce the .tess file, whose image I have attached here.

2) Mesh Tessellation 

```
neper -M n50-id1.tess -elt tet
```

which returned the following output -

```
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.                       
Info   : Version 4.1.0                       
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt           
Info   : Running on 8 threads.                       
Info   : <https://neper.info>                   
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.   
Info   : No initialization file found (`/home/aadi/.neperrc').  
Info   : ---------------------------------------------------------------  
Info   : MODULE  -M loaded with arguments:         
Info   : [ini file] (none)            
Info   : [com line] n50-id1.tess -elt tet   
Info   : ---------------------------------------------------------------                                                    
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n50-id1.tess'...
Info   :     [i] Parsed file `n50-id1.tess'.   
Info   : Meshing...
Info   :   - Preparing... (cl = 0.3125) 100%  
Info   :   - 0D meshing... 100%      
Info   :   - 1D meshing... 100%  
Info   :   - 2D meshing...   3% (0|0.76/90%|10%| 0%)Error  :     > Meshing of face 1 failed  
Aborted (core dumped)                                                                         
```

All packages I compiled Neper with were installed using sudo apt install. For meshing, I manually installed gmsh version 4.6.0, which is their most current stable version on the gitlab repo.

![cylinder](https://user-images.githubusercontent.com/11017915/97807392-71e77680-1c2e-11eb-87a0-6d4576f3dd5d.png)

Please let me know if you need any more information regarding the Neper or gmsh building and installation process. 

Best,
Aaditya

**Comment by rquey** [comment]
Did you run the tests (`make test`)? because it is like if Gmsh was not properly installed (or found by Neper).

**Comment by aaditya8959** [comment]
I did run make test and some tests did fail. Looking at the 'LastTestsFailed.log' file the following tests had failed :

125:M_rcl_expr                                                                                                                                                      126:M_dim                                                                                                                                                           127:M_dim2                                                                                                                                                          128:M_dim_expr                                                                                                                                                      129:M_order                                                                                                                                                         133:M_pl                                                                                                                                                            137:M_meshqualexpr                                                                                                                                                  138:M_meshqualdisexpr                                                                                                                                               140:M_mesh2dalgo_dela                                                                                                                                               144:M_mesh3dalgo_netggmsh                                                                                                                                           145:M_mesh3dalgo_netggmne                                                                                                                                           152:M_remesh1                                                                                                                                                       154:M_remesh3                                                                                                                                                       157:M_nset3                                                                                                                                                         172:M_interface                                                                                                                                                     180:V_pretest5                                                                                                                                                      257:V_nodecoo                                                                                                                                                       258:V_nodecoo_disp                                                                                                                                                  259:V_nodecoofact                                                                                                                                                   261:V_slicemesh2                                                                                                                                                    273:V_cameracoo2                                                                                                                                                    274:V_cameracoo3                                                                                                                                                    285:V_loop 

Before installing gmsh manually I had also tried with an installing of gmsh via sudo apt install. In that case more tests had failed because of which I switched to the manual installation. I will check what the issue with my installation of gmsh might be. How would you recommend installing gmsh? Is there a specific version and installation procedure that worked for you? Thank you for your help.

Best,
Aaditya

**Comment by rquey** [comment]
Gmsh is way faster when installed "manually", but make sure to resolve all dependencies (which are listed when you run `cmake ..`). Any Gmsh version works.

**Comment by aaditya8959** [comment]
I reinstalled gmsh(version 4.6.0) from the source code, after installing OpenCASCADE and FLTK libraries as prerequisites. I also installed libScotch from the source code after which I reinstalled Neper(version 4.1.0). Running the tests as 

make -j12 test 

resulting in failure for the following tests : 

119:M_rcl
124:M_cl_expr
127:M_dim2
128:M_dim_expr
133:M_pl
138:M_meshqualdisexpr
139:M_mesh2dalgo_mead
140:M_mesh2dalgo_dela
141:M_mesh2dalgo_fron
142:M_mesh2dalgo_netg
143:M_mesh3dalgo_netgnetg
145:M_mesh3dalgo_netggmne                                                                                                                                                           158:M_faset
180:V_pretest5
257:V_nodecoo
258:V_nodecoo_disp
259:V_nodecoofact
261:V_slicemesh2
273:V_cameracoo2
274:V_cameracoo3
285:V_loop  

I still proceeded though and tested the creation of a cylindrical tessellation and it's meshing with tetrahedral elements as follows :

neper -T -n 50 -domain 'cylinder(4,2)'  -reg 1

which ran successfully after which 

neper -M n50-id1.tess -elt tet

resulted in the following output(and error) :
                                                                                                                                                                                    ========================    N   e   p   e   r    =======================                                                                                                            Info   : A software package for polycrystal generation and meshing.                                                                                                                 Info   : Version 4.1.0                                                                                                                                                              Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)                                                                                                             Info   : Running on 4 threads.                                                                                                                                                      Info   : <https://neper.info>                                                                                                                                                       Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.                                                                                                                    Info   : No initialization file found (`/home/aadi/.neperrc').                                                                                                                      Info   : ---------------------------------------------------------------                                                                                                            Info   : MODULE  -M loaded with arguments:                                                                                                                                          Info   : [ini file] (none)                                                                                                                                                          Info   : [com line] n50-id1.tess -elt tet                                                                                                                                           Info   : ---------------------------------------------------------------                                                                                                            Info   : Reading input data...                                                                                                                                                      Info   :   - Reading arguments...                                                                                                                                                   Info   : Loading input data...                                                                                                                                                      Info   :   - Loading tessellation...                                                                                                                                                Info   :     [i] Parsing file `n50-id1.tess'...                                                                                                                                     Info   :     [i] Parsed file `n50-id1.tess'.                                                                                                                                        Info   : Meshing...                                                                                                                                                                 Info   :   - Preparing... (cl = 0.3125) 100%                                                                                                                                        Info   :   - 0D meshing... 100%                                                                                                                                                     Info   :   - 1D meshing... 100%                                                                                                                                                     Info   :   - 2D meshing...   3% (0|0.73/89%|11%| 0%)Error  :     > Meshing of face 9 failed                                                                                         Aborted (core dumped)      

So I cleared the tmp files generated as a result of the error and ran the same command but in the presence of a debugger as follows : 

rm tmp*
gdb --args  neper -M n50-id1.tess -elt tet  

after which running produces the following output(and error) : 

Starting program: /home/aadi/neper_install/bin/neper -M n50-id1.tess -elt tet                                                                                                       [Thread debugging using libthread_db enabled]                                                                                                                                       Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".                                                                                                                                                                                                                                                                                              ========================    N   e   p   e   r    =======================                                                                                                            Info   : A software package for polycrystal generation and meshing.                                                                                                                 Info   : Version 4.1.0                                                                                                                                                              Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)                                                                                                             [New Thread 0x7ffffcc50700 (LWP 14090)]                                                                                                                                             [New Thread 0x7ffffc440700 (LWP 14091)]                                                                                                                                             [New Thread 0x7ffffbc30700 (LWP 14092)]                                                                                                                                             Info   : Running on 4 threads.                                                                                                                                                      Info   : <https://neper.info>                                                                                                                                                       Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.                                                                                                                    Info   : No initialization file found (`/home/aadi/.neperrc').                                                                                                                      Info   : ---------------------------------------------------------------                                                                                                            Info   : MODULE  -M loaded with arguments:                                                                                                                                          Info   : [ini file] (none)                                                                                                                                                          Info   : [com line] n50-id1.tess -elt tet                                                                                                                                           Info   : ---------------------------------------------------------------                                                                                                            Info   : Reading input data...                                                                                                                                                      Info   :   - Reading arguments...                                                                                                                                                   Info   : Loading input data...                                                                                                                                                      Info   :   - Loading tessellation...                                                                                                                                                Info   :     [i] Parsing file `n50-id1.tess'...                                                                                                                                     Info   :     [i] Parsed file `n50-id1.tess'.                                                                                                                                        Info   : Meshing...                                                                                                                                                                 Info   :   - Preparing... (cl = 0.3125) 100%                                                                                                                                        Info   :   - 0D meshing... 100%                                                                                                                                                     Info   :   - 1D meshing... 100%                                                                                                                                                     Info   :   - 2D meshing...   2% (0|0.73/87%|13%| 0%)Error  :     > Meshing of face 8 failed                                                                                                                                                                                                                                                                             Thread 1 "neper" received signal SIGABRT, Aborted.                                                                                                                                  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                                                                               51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory. 

Have you encountered the above error before? I am trying to install all of this on my Windows Subsystem for Linux(Ubuntu 18.04). Thank you.

Best,
Aaditya

**Comment by rquey** [comment]
> I am trying to install all of this on my Windows Subsystem for Linux(Ubuntu 18.04). 

So, it is likely a multithreading issue (see #74). Try to recompile Neper with multithreading off:
```
cmake -DHAVE_OPENMP=OFF ..
make
make test
```

**Comment by aaditya8959** [comment]
I recompiled neper with OpenMP dependency set to OFF and it worked just fine. Thanks a lot for your help and the multithreading issue link you shared. This issue seems specific to the windows subsystem for linux. 
![image_2](https://user-images.githubusercontent.com/11017915/97962394-18449080-1d83-11eb-8769-a4f7cfcb7a06.png)

**Comment by rquey** [comment]
Great. Neper will run significantly slower, though.
