### ISSUE TITLE
2D mesh error; bad meshing parameters for edge1: c1=0.0000 p1=2.0000

### ISSUE THREAD

**Issue by Adam-S-Yanxuan** [rquey/neper#81]
neper -T -n 100 -id 2 -dim 2 -domain "square(0.5,0.2)" -transform "cut(cylinder(0.3,0.35,,0,0,1,0.2))"
neper -M n100-id2.tess
![image](https://user-images.githubusercontent.com/44885484/99338141-9b570200-28be-11eb-8c6d-6785a26f83e7.png)
the figure of -T was as follows:
![image_1](https://user-images.githubusercontent.com/44885484/99338273-da855300-28be-11eb-8e9e-85eaa1672508.png)

**Comment by rquey** [comment]
This was fixed in 1f23adfe6340ce128ba39ce302ae1aa2dd3556a6. Use the latest version.
