### ISSUE TITLE
Segmentation fault (core dumped) when visualizing multiscale tessellation

### ISSUE THREAD

**Issue by chandlerchenn** [rquey/neper#82]
Hi, 

I am new to neper, and I met one problem today when I tried the examples on the neper website.
The command lines I input is: `neper -T -n 200::from_morpho -morpho 'gg::lamellar(w=0.02)' \ -o gene_mult_1` and `neper -V gene_mult_1.tess -datacellcol 'scaleid(1)' -print gene_mult_1`.

The first -T command line worked well, I get gene_mult_1.tess file successfully. However, the second -V command line give me a Segmentation fault (core dumped) error showing in this picture.
![捕获](https://user-images.githubusercontent.com/74768082/99792125-9bc2f780-2b61-11eb-9345-201625bf47db.JPG)

I suspect the error might have something related with "scaleid(1)", but I don't know how to resolve it. Can you please give me any suggestion on how to fix it?

Jingwei

**Comment by rquey** [comment]
Thanks @chandlerchenn for the bug report.  This is fixed in version 4.1.1-3.
