### ISSUE TITLE
Extracting grain average values from FEpX output using Neper

### ISSUE THREAD

**Issue by darrencpagan** [rquey/neper#83]
@rquey @mkasemer

I was wondering what is the best way to extract grain average values from FEpX using Neper? Currently using FEpX 1.0.1 and Neper 4.1.

I'd like to extract grain average orientation and stress.

Thank you,
Darren

**Comment by mkasemer** [comment]
@rquey - I was unsure if this manipulation was available yet in Neper, or just the basic concatenation post-processing.

Also, I'm not sure if your orilib routines handle orientation averaging already. If so, could you please comment on the method used? I've been partial to the top answer [https://stackoverflow.com/questions/12374087/average-of-multiple-quaternions](here).

**Comment by rquey** [comment]
@darrencpagan It would be using -S. That's part of the plan. Let me a few days...

@mkasemer It sure does. It's described in [Orilib's doc](neper.info/docs/orilib.pdf), page 47-48 (references to actual paper's can be found there). I don't think the answer you pointed to applies when there is crystal symmetry.

**Comment by darrencpagan** [comment]
That sounds great, let me know if it goes live!

Also, is there any way to establish the connectivity of grains? Which grains are touching which? I imagine this could be done from the tesselation?

**Comment by rquey** [comment]
Sure.

For the neighbors, that's `-statcell ncells` (see also `ncellnb`) - section A.2 of the doc.

**Comment by darrencpagan** [comment]
@rquey  Thank you. I think the -statcell ncells command was what I was looking for.

Just to confirm, the output seems to be a row for each cell (grain), with a list of integers on each row which are the neighboring cells (grains)?

**Comment by rquey** [comment]
Yes, this is what it is.

**Comment by rquey** [comment]
@darrencpagan This is now possible using `-elsetres stress,ori`.

**Comment by darrencpagan** [comment]
@rquey Will I be able to access these features with the current public version of Neper?

**Comment by rquey** [comment]
Yes, it is live in v4.1.1.
