### ISSUE TITLE
I have question：The arc shape is simplified as lines.

### ISSUE THREAD

**Issue by Adam-S-Yanxuan** [rquey/neper#84]
I was investigated the effect of successive round shaped notch considering microstructure.
However, the geometry was really hard to create for the limited number of edges of a single crystal.
The geometry of my work was marked as red circles. 
Obviously the curve was too "rough".
How can I increase the edge limitation of a single crystal to make my geometry finer?
![image](https://user-images.githubusercontent.com/44885484/99940645-8ccd8680-2da7-11eb-946b-8988ca4c8f3a.png)

**Comment by rquey** [comment]
The edges of a tessellation are shown as segments even when they are curved.  The mesh, at the opposite, will look curved.

If you are aiming at a single crystal, you can merge all cells a posteriori, using `mergecell`.

**Comment by Adam-S-Yanxuan** [comment]
Sorry, I may not have described my problem clearly.
What I'm doing is a polycrystalline calculation.
But what I study is the effect of geometry on mechanical properties.
Therefore, more precise geometry is required like this:
![image](https://user-images.githubusercontent.com/44885484/99944842-8b538c80-2dae-11eb-94d6-d9d773c9d33c.png)

However, when I do -T with neper, the geometry of a circle is roughly divided into several segments.
![image](https://user-images.githubusercontent.com/44885484/99950778-0b322480-2db8-11eb-8852-d6bb2c64bef8.png)

Is there any technique to get a better geometry?
![image](https://user-images.githubusercontent.com/44885484/99951783-9829ad80-2db9-11eb-8cdf-74a99322d42b.png)

________________________
Thank you very much!
My English is not very good. Hope you can understand me now.
Best regards.

**Comment by rquey** [comment]
This should not be happening. See below:
```
neper -T -n 100 -domain "cube(1,1,0.2)"  -transform "cut(cylinder(0.5,1.5,0.4,0,1,0,0.3))" -reg 1 -id 5
neper -M n100-id5.tess -rcl 0.5
neper -V n100-id5.tess,n100-id5.msh -cameraangle 14 -print img
neper -V n100-id5.tess,n100-id5.msh -dataelsetcol id -cameracoo x:-4:z -cameraprojection orthographic -cameraangle 14 -print img2
```
![image](https://user-images.githubusercontent.com/2659376/101914681-e1a13780-3bc4-11eb-97e8-b8209c167d4b.png)
![image](https://user-images.githubusercontent.com/2659376/101914834-13b29980-3bc5-11eb-9266-17aa482e7eea.png)
