### ISSUE TITLE
How to update the neper from 3- to 4- version

### ISSUE THREAD

**Issue by SUNLOVEERIN** [rquey/neper#85]
Hi everyone,

I am a user of 3.5.3 version of neper, i was wondering how to update to the newest version.
I am run the neper onUbuntu, how to update it by codes?

Thank you so much for your help in advance.
Sincerely

**Comment by rquey** [comment]
Check out [Neper's download page](https://neper.info/downloads.html).  Detailed installation instructions are provided in the PDF documentation.

**Comment by SUNLOVEERIN** [comment]
> Check out [Neper's download page](https://neper.info/downloads.html). Detailed installation instructions are provided in the PDF documentation.

Thank you so much for your help.

**Comment by SUNLOVEERIN** [comment]
> Check out [Neper's download page](https://neper.info/downloads.html). Detailed installation instructions are provided in the PDF documentation.

Hi, I was wondering whether I should reinstall the whole neper instead of just update it? I haven't found any code to update it yet.
Thank you so much for your help in advance.

**Comment by rquey** [comment]
The simplest way is to [download the archive](https://neper.info/downloads.html) and install following the instructions of the PDF documentation available on the same page.

*Update* would be if you had a local Git repo for the sources...

**Comment by SUNLOVEERIN** [comment]
Dear rquey

I followed the instructions then when I did this step:
![image](https://user-images.githubusercontent.com/53950096/100241680-4dee2b00-2f77-11eb-96c3-6ff63315de4e.png)

error message comes out:
![image](https://user-images.githubusercontent.com/53950096/100241723-5b0b1a00-2f77-11eb-8895-3a3d870cb167.png)
How can I do to solve this problem?

Thank you so much for your help.
Sincerely

**Comment by avillani** [comment]
this is weird, I see no source file building in your output, such as this:

```
[ 98%] Building CXX object neper_t/CMakeFiles/neper_t.dir/net_ori/net_ori_uniform/net_ori_uniform5.cpp.o
[ 98%] Building C object neper_t/CMakeFiles/neper_t.dir/net_domain/net_domain_cube/net_domain_cube3.c.o
[ 99%] Building C object neper_t/CMakeFiles/neper_t.dir/net_dim/net_dim1.c.o
[ 99%] Building C object neper_t/CMakeFiles/neper_t.dir/neper_t.c.o
[ 99%] Linking CXX static library libneper_t.a
[ 99%] Built target neper_t
Scanning dependencies of target neper
[100%] Building C object CMakeFiles/neper.dir/neper.c.o
[100%] Linking CXX executable neper
[100%] Built target neper
```
There was no error in the cmake phase ?

**Comment by rquey** [comment]
Thanks @avillani  for jumping in.

@SUNLOVEERIN, please provide your full terminal output as *text*, not screenshots.  You can copy-paste your terminal output and format it as code using markdown (enclose it between "```" lines). You can also *preview* your message...

**Comment by SUNLOVEERIN** [comment]
@rquey @avillani 
Dear rquey and avillani
Thank you for your timely reply

The  closed the terminal before, then I just deleted the "build" fold then rerun the code, the code of cmake are attached here:

m@m:~/neper-4.1.1/neper-4.1.1/src/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at neper_t/CMakeLists.txt:41 (add_library):
  Cannot find source file:

    ./net_tess/net_tess_opt/net_tess_opt_comp/net_tess_opt_comp_objective/net_tess_opt_comp_objective_fval/net_tess_opt_comp_objective_fval_gen/net_tess_opt_comp_objective_fval_gen_stat/net_tess_opt_comp_objective_fval_gen_stat1.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Generating done
-- Build files have been written to: /home/m/neper-4.1.1/neper-4.1.1/src/build

It seems like something wrong already happens here, neper 3.5.3 has installed in this Ubuntu subsystem, I cannot understand.
Thank you again.

**Comment by avillani** [comment]
I just tested from the github source, it's ok on my side. How did you obtained the sources ? Zip download from github, git clone , neper.info website ?

Did you check the file was indeed mising on your disk ? Should be in `src/neper_t/net_tess/net_tess_opt/net_tess_opt_comp/net_tess_opt_comp_objective/net_tess_opt_comp_objective_fval/net_tess_opt_comp_objective_fval_gen/net_tess_opt_comp_objective_fval_gen_stat/net_tess_opt_comp_objective_fval_gen_stat1.c`

**Comment by SUNLOVEERIN** [comment]
> I just tested from the github source, it's ok on my side. How did you obtained the sources ? Zip download from github, git clone , neper.info website ?
> 
> Did you check the file was indeed mising on your disk ? Should be in `src/neper_t/net_tess/net_tess_opt/net_tess_opt_comp/net_tess_opt_comp_objective/net_tess_opt_comp_objective_fval/net_tess_opt_comp_objective_fval_gen/net_tess_opt_comp_objective_fval_gen_stat/net_tess_opt_comp_objective_fval_gen_stat1.c`

Dear avillani

I found I really missed this file, after re-downloading the archive, all installation has been done, I updated to the latest version.
Thank you so much for your help.
Sincerely
