### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shahramkhazaee** [rquey/neper#87]
Dear Romain, 

I need to generate a hex-type mesh in an abaqus file format and I always get the segmentation fault error (not with .msh file format but only with .inp one). The following example (being a very short simulation) was already asked by someone and you answered him that updating will resolve the problem: 
> neper -T -n 250 -id 1 -domain 'cube(21,21,21)' -o 'abaqus_file'   ===> [works]
> neper -M abaqus_file.tess -elttype hex -cl 1 -format inp              ===> [segmentation fault]
             
I tried to use different versions of Neper without any success (even using the last version 4.1.1). 
Do you have any idea why it does not work? 

Many thanks in advance.
Best regards,
Shahram K.

**Comment by rquey** [comment]
This is now fixed.  Thanks @shahramkhazaee for the bug report.
