### ISSUE TITLE
cannot set camera position, figure transparency ...

### ISSUE THREAD

**Issue by Adam-S-Yanxuan** [rquey/neper#88]
sudo neper -V n150-id1.tess -datacellcol id -print image_1 -datacelltrs 0.5
![image](https://user-images.githubusercontent.com/44885484/101593942-d1a22000-3a2b-11eb-8498-b24812b24181.png)

**Comment by rquey** [comment]
The order of the arguments matters in -V. Use `neper -V n150-id1.tess -datacellcol id  -datacelltrs 0.5 -print image_1`, and do not use `sudo`, if possible...
