### ISSUE TITLE
Error when writing inp file with hex elements 

### ISSUE THREAD

**Issue by GretheWinther** [rquey/neper#89]
Hi Romain,

When executing 
neper -T -n 10 -o test
neper -M test.tess -elttype hex  -format inp 

an error is reported:
Info   :   - Writing mesh...
Info   :     [o] Writing file 'test.inp'
testNeper2.sh: line 2: 24196 Segmentation fault    (core dumped) neper -M test.tess -elttype hex -format inp

A test.inp is made but ends incomplete:
*Elset, elset=poly10
228, 237, 238, 246, 247, 255, 256, 257, 265, 266, 309, 318, 319, 326,
327, 328, 329, 335, 336, 337, 338, 343, 344, 345, 346, 347, 348, 354,
355, 356, 357, 358, 365, 366, 367, 368, 376, 377, 378, 387, 410, 418,
419, 426, 427, 428, 429, 435, 436, 437, 438, 439, 443, 444, 445, 446,
447, 448, 449, 453, 454, 455, 456, 457, 458, 459, 465, 466, 467, 468,
476, 477, 478, 487, 488, 498, 510, 518, 519, 520, 527, 528, 529, 530,
535, 536, 537, 538, 539, 540, 544, 545, 546, 547, 548, 549, 554, 555,
556, 557, 558, 559, 565, 566, 567, 568, 569, 576, 577, 578, 579, 587,
588, 589, 619, 627, 628, 629, 630, 635, 636, 637, 638, 639, 640, 644,
645, 646, 647, 

This is with version 4.1.1. I have executed similar commands without problems in version 3.5.0. I have not tried versions in between. The error does not occur for tet elements.

Best regards,

Grethe

**Comment by GretheWinther** [comment]
Hi Romain,

Thanks for a quick reply. I will install the development version.

We have started using neper both with fepx and DAMASK. I find it a lot easier to work with than Dream3D. We are also very pleased with the possibilities of making tessellations designed to get both size and position right with respect to 3DXRD data.

Thanks for providing this very useful tool,

Grethe

**Comment by rquey** [comment]
Glad I can help. If you find Neper slow when fitting 3DXRD data, you can increase the tolerance using `-morphooptistop eps=...` (default `1e-6`).  Neper uses the same default tolerance for all input data (statistical, tesr, 3DXRD, etc.), but it is rather low and only slowly reached for 3DXRD data, compared to other (proper) inputs.
