### ISSUE TITLE
Tess from tesr file

### ISSUE THREAD

**Issue by darrencpagan** [rquey/neper#90]
Hi @rquey ,

@mkasemer and I were trying to build a tess file (then mesh) from a tesr file built from near field HEDM data. We are using a tesr format and command that has worked previously but are now getting an error. We are using Neper 4.1.0.

Command:
```
neper -T -n from_morpho -domain 'cube(0.96,0.96,1)' -morpho 'tesr:file(ni_map.tesr)' -morphooptiobjective 'pts(region=surf,res=5)' -morphooptistop itermax=30 -reg 1 -o ni_test
```

Error:
```
========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.1.0
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt|libscotch (full)
Info   : Running on 80 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/faculty/dcp5303/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n from_morpho -domain cube(0.96,0.96,1) -morpho
         tesr:file(ni_map.tesr) -morphooptiobjective
         pts(region=surf,res=5) -morphooptistop itermax=30 -reg 1 -o
         ni_test
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :     [i] Parsing file `ni_map.tesr'...
Info   :     [i] Parsed file `ni_map.tesr'.
Info   :       . Number of cells: 36
Info   :   - Setting seeds... 100%
100%
Info   :   - Generating crystal orientations...
Error  :       . Failed to process expression `pts(region=surf,res=5)'.
Aborted (core dumped)
```

Do you know what the issue might be?

Thanks,
Darren

**Comment by rquey** [comment]
Hi Darren,

Short answer: `-morphooptiobjective` is causing the issue, but you are actually calling it with its default value, so you can just remove that option from your command.

**Comment by mkasemer** [comment]
Thanks - that seems to have worked. Is there something wrong with the command as we typed it?

**Comment by rquey** [comment]
No - it's just an internal bug, which I'm fixing right now.

**Comment by rquey** [comment]
Okay - there was no actual bug.  It is the option argument that was not correct, as it should have followed the syntax "_variable_:_value_" to be `"tesr:pts(region=surf,res=5)"`.

This was not very easy to get from the documentation... I improved it by including actual examples for this option (and I also slightly improved the code).
