### ISSUE TITLE
Error: Aborted (core dumped) on meshes

### ISSUE THREAD

**Issue by whishei** [rquey/neper#93]
Hi,
I just recently installed Neper this week and have been running into an issue with meshing. I had the software working earlier in the week, but I tried to install Neper on VirtualBox as well and ran into an issue with an overlapping file. Since then, I deleted everything and started over, but I am now facing an issue when I attempt to run any meshes on Neper. The tessellations are working fine, just the meshes are causing an issue. I would appreciate any help you can give me or any feedback. 

Another unrelated question I had was whether or not Neper allows for users to put in their own distribution function, or are the built-in options the only available options? 

```
$ neper -T -n 100 -id 1

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.1.1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/whishei/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -T loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] -n 100 -id 1
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   : Creating domain...
Info   : Creating tessellation...
Info   :   - Setting seeds...
Info   :   - Generating crystal orientations...
Info   :   - Running tessellation...
Info   : Writing results...
Info   :     [o] Writing file `n100-id1.tess'...
Info   :     [o] Wrote file `n100-id1.tess'.
Info   : Elapsed time: 0.115 secs.
========================================================================

$ neper -M n100-id1.tess -meshqualmin 1

========================    N   e   p   e   r    =======================
Info   : A software package for polycrystal generation and meshing.
Info   : Version 4.1.1
Info   : Built with: gsl|muparser|opengjk|openmp|nlopt
Info   : Running on 4 threads.
Info   : <https://neper.info>
Info   : Copyright (C) 2003-2020, and GNU GPL'd, by Romain Quey.
Info   : No initialization file found (`/home/whishei/.neperrc').
Info   : ---------------------------------------------------------------
Info   : MODULE  -M loaded with arguments:
Info   : [ini file] (none)
Info   : [com line] n100-id1.tess -meshqualmin 1
Info   : ---------------------------------------------------------------
Info   : Reading input data...
Info   :   - Reading arguments...
Info   : Loading input data...
Info   :   - Loading tessellation...
Info   :     [i] Parsing file `n100-id1.tess'...
Info   :     [i] Parsed file `n100-id1.tess'.
Info   : Meshing...
Info   :   - Preparing... (cl = 0.1077) 100%
Info   :   - 0D meshing... 100%
Info   :   - 1D meshing... 100%
Info   :   - 2D meshing...   2% (0|0.53/92%| 8%| 0%)Error  :     > Meshing of face 12 failed
Aborted (core dumped)
```

**Comment by rquey** [comment]
Gmsh does not seem to be installed / found.

**Comment by whishei** [comment]
If I look just for Gmsh, it appears to be installed. However, I'm new to the Linux system, so I may be wrong. These commands work however. Could I be missing dependencies that are necessary? 

$ gmsh -help
Gmsh, a 3D mesh generator with pre- and post-processing facilities
Copyright (C) 1997-2020 C. Geuzaine and J.-F. Remacle
Usage: gmsh [options] [files]
...

$ gmsh -version
4.7.1

**Comment by whishei** [comment]
Thank you for your help. My system was not able to recongize Gmsh, but I uninstalled everything and Neper is working now. I had two additional questions if that's okay: 
Is there a way to calculate the generated mesh quality to see how it relates to the specified meshqualmin?    and
Does Neper allow for users to put in their own distribution function, or are the built-in options the only available options?
Thank you!

**Comment by rquey** [comment]
> Is there a way to calculate the generated mesh quality to see how it relates to the specified meshqualmin?

Yes, see `-statelt rr`.

> Does Neper allow for users to put in their own distribution function, or are the built-in options the only available options?

I'm working on the import of user-defined distribution.
